// <auto-generated />
namespace Anatoli.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StockProductRule4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockProductRule4));
        
        string IMigrationMetadata.Id
        {
            get { return "201601081821204_Stock-Product-Rule-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
