namespace Anatoli.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PermissionMigration2 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.BankAccounts", "AddedById", c => c.Guid());
            AddColumn("dbo.BankAccounts", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.BaseTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.BaseTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.BaseValues", "AddedById", c => c.Guid());
            AddColumn("dbo.BaseValues", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.BasketItems", "AddedById", c => c.Guid());
            AddColumn("dbo.BasketItems", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Baskets", "AddedById", c => c.Guid());
            AddColumn("dbo.Baskets", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.BasketNotes", "AddedById", c => c.Guid());
            AddColumn("dbo.BasketNotes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Customers", "AddedById", c => c.Guid());
            AddColumn("dbo.Customers", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Companies", "AddedById", c => c.Guid());
            AddColumn("dbo.Companies", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CompanyCenters", "AddedById", c => c.Guid());
            AddColumn("dbo.CompanyCenters", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Stocks", "AddedById", c => c.Guid());
            AddColumn("dbo.Stocks", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockOnHandSyncs", "AddedById", c => c.Guid());
            AddColumn("dbo.StockOnHandSyncs", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockActiveOnHands", "AddedById", c => c.Guid());
            AddColumn("dbo.StockActiveOnHands", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Products", "AddedById", c => c.Guid());
            AddColumn("dbo.Products", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CharValues", "AddedById", c => c.Guid());
            AddColumn("dbo.CharValues", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CharTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.CharTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CharGroups", "AddedById", c => c.Guid());
            AddColumn("dbo.CharGroups", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.IncompletePurchaseOrderLineItems", "AddedById", c => c.Guid());
            AddColumn("dbo.IncompletePurchaseOrderLineItems", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.IncompletePurchaseOrders", "AddedById", c => c.Guid());
            AddColumn("dbo.IncompletePurchaseOrders", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CityRegions", "AddedById", c => c.Guid());
            AddColumn("dbo.CityRegions", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Stores", "AddedById", c => c.Guid());
            AddColumn("dbo.Stores", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StoreActions", "AddedById", c => c.Guid());
            AddColumn("dbo.StoreActions", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StoreActiveOnhands", "AddedById", c => c.Guid());
            AddColumn("dbo.StoreActiveOnhands", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StoreActivePriceLists", "AddedById", c => c.Guid());
            AddColumn("dbo.StoreActivePriceLists", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StoreCalendars", "AddedById", c => c.Guid());
            AddColumn("dbo.StoreCalendars", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StoreCalendarHistories", "AddedById", c => c.Guid());
            AddColumn("dbo.StoreCalendarHistories", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CalendarTemplates", "AddedById", c => c.Guid());
            AddColumn("dbo.CalendarTemplates", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CalendarTemplateHolidays", "AddedById", c => c.Guid());
            AddColumn("dbo.CalendarTemplateHolidays", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CalendarTemplateOpenTimes", "AddedById", c => c.Guid());
            AddColumn("dbo.CalendarTemplateOpenTimes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StoreDeliveryPersons", "AddedById", c => c.Guid());
            AddColumn("dbo.StoreDeliveryPersons", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.DeliveryPersons", "AddedById", c => c.Guid());
            AddColumn("dbo.DeliveryPersons", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CustomerShipAddresses", "AddedById", c => c.Guid());
            AddColumn("dbo.CustomerShipAddresses", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrders", "AddedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrders", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderClearances", "AddedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderClearances", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderStatusHistories", "AddedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderStatusHistories", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderLineItems", "AddedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderLineItems", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderPayments", "AddedById", c => c.Guid());
            AddColumn("dbo.PurchaseOrderPayments", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.MainProductGroups", "AddedById", c => c.Guid());
            AddColumn("dbo.MainProductGroups", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestRules", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestRules", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequests", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequests", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestProducts", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestProducts", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestProductDetails", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestProductDetails", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestStatus", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestStatus", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestSupplyTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestSupplyTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProducts", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProducts", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.FiscalYears", "AddedById", c => c.Guid());
            AddColumn("dbo.FiscalYears", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ReorderCalcTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.ReorderCalcTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.StockTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Suppliers", "AddedById", c => c.Guid());
            AddColumn("dbo.Suppliers", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestRuleCalcTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestRuleCalcTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestRuleTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.StockProductRequestRuleTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Manufactures", "AddedById", c => c.Guid());
            AddColumn("dbo.Manufactures", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductComments", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductComments", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductGroups", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductGroups", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductPictures", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductPictures", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductRates", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductRates", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductTagValues", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductTagValues", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductTags", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductTags", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.StockHistoryOnHands", "AddedById", c => c.Guid());
            AddColumn("dbo.StockHistoryOnHands", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CustomerAreas", "AddedById", c => c.Guid());
            AddColumn("dbo.CustomerAreas", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.RegionAreas", "AddedById", c => c.Guid());
            AddColumn("dbo.RegionAreas", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityDayAreas", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityDayAreas", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CompanyPersonnels", "AddedById", c => c.Guid());
            AddColumn("dbo.CompanyPersonnels", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CompanyOrgCharts", "AddedById", c => c.Guid());
            AddColumn("dbo.CompanyOrgCharts", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityEvents", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityEvents", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityEventTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityEventTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityVisitTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityPoints", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityPoints", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.RegionAreaLevelTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.RegionAreaLevelTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.RegionAreaPoints", "AddedById", c => c.Guid());
            AddColumn("dbo.RegionAreaPoints", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.Clearances", "AddedById", c => c.Guid());
            AddColumn("dbo.Clearances", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.CompanyPersonnelRoutes", "AddedById", c => c.Guid());
            AddColumn("dbo.CompanyPersonnelRoutes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.DiscountCodes", "AddedById", c => c.Guid());
            AddColumn("dbo.DiscountCodes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ItemImages", "AddedById", c => c.Guid());
            AddColumn("dbo.ItemImages", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityCommentTypes", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityEventComments", "AddedById", c => c.Guid());
            AddColumn("dbo.PersonnelDailyActivityEventComments", "LastModifiedById", c => c.Guid());
            AddColumn("dbo.ProductSupplierGuarantees", "AddedById", c => c.Guid());
            AddColumn("dbo.ProductSupplierGuarantees", "LastModifiedById", c => c.Guid());
            CreateIndex("dbo.BankAccounts", "AddedById");
            CreateIndex("dbo.BankAccounts", "LastModifiedById");
            CreateIndex("dbo.BaseTypes", "AddedById");
            CreateIndex("dbo.BaseTypes", "LastModifiedById");
            CreateIndex("dbo.BaseValues", "AddedById");
            CreateIndex("dbo.BaseValues", "LastModifiedById");
            CreateIndex("dbo.BasketItems", "AddedById");
            CreateIndex("dbo.BasketItems", "LastModifiedById");
            CreateIndex("dbo.Baskets", "AddedById");
            CreateIndex("dbo.Baskets", "LastModifiedById");
            CreateIndex("dbo.BasketNotes", "AddedById");
            CreateIndex("dbo.BasketNotes", "LastModifiedById");
            CreateIndex("dbo.Customers", "AddedById");
            CreateIndex("dbo.Customers", "LastModifiedById");
            CreateIndex("dbo.Companies", "AddedById");
            CreateIndex("dbo.Companies", "LastModifiedById");
            CreateIndex("dbo.CompanyCenters", "AddedById");
            CreateIndex("dbo.CompanyCenters", "LastModifiedById");
            CreateIndex("dbo.Stocks", "AddedById");
            CreateIndex("dbo.Stocks", "LastModifiedById");
            CreateIndex("dbo.StockOnHandSyncs", "AddedById");
            CreateIndex("dbo.StockOnHandSyncs", "LastModifiedById");
            CreateIndex("dbo.StockActiveOnHands", "AddedById");
            CreateIndex("dbo.StockActiveOnHands", "LastModifiedById");
            CreateIndex("dbo.Products", "AddedById");
            CreateIndex("dbo.Products", "LastModifiedById");
            CreateIndex("dbo.CharValues", "AddedById");
            CreateIndex("dbo.CharValues", "LastModifiedById");
            CreateIndex("dbo.CharTypes", "AddedById");
            CreateIndex("dbo.CharTypes", "LastModifiedById");
            CreateIndex("dbo.CharGroups", "AddedById");
            CreateIndex("dbo.CharGroups", "LastModifiedById");
            CreateIndex("dbo.IncompletePurchaseOrderLineItems", "AddedById");
            CreateIndex("dbo.IncompletePurchaseOrderLineItems", "LastModifiedById");
            CreateIndex("dbo.IncompletePurchaseOrders", "AddedById");
            CreateIndex("dbo.IncompletePurchaseOrders", "LastModifiedById");
            CreateIndex("dbo.CityRegions", "AddedById");
            CreateIndex("dbo.CityRegions", "LastModifiedById");
            CreateIndex("dbo.Stores", "AddedById");
            CreateIndex("dbo.Stores", "LastModifiedById");
            CreateIndex("dbo.StoreActions", "AddedById");
            CreateIndex("dbo.StoreActions", "LastModifiedById");
            CreateIndex("dbo.StoreActiveOnhands", "AddedById");
            CreateIndex("dbo.StoreActiveOnhands", "LastModifiedById");
            CreateIndex("dbo.StoreActivePriceLists", "AddedById");
            CreateIndex("dbo.StoreActivePriceLists", "LastModifiedById");
            CreateIndex("dbo.StoreCalendars", "AddedById");
            CreateIndex("dbo.StoreCalendars", "LastModifiedById");
            CreateIndex("dbo.StoreCalendarHistories", "AddedById");
            CreateIndex("dbo.StoreCalendarHistories", "LastModifiedById");
            CreateIndex("dbo.CalendarTemplates", "AddedById");
            CreateIndex("dbo.CalendarTemplates", "LastModifiedById");
            CreateIndex("dbo.CalendarTemplateHolidays", "AddedById");
            CreateIndex("dbo.CalendarTemplateHolidays", "LastModifiedById");
            CreateIndex("dbo.CalendarTemplateOpenTimes", "AddedById");
            CreateIndex("dbo.CalendarTemplateOpenTimes", "LastModifiedById");
            CreateIndex("dbo.StoreDeliveryPersons", "AddedById");
            CreateIndex("dbo.StoreDeliveryPersons", "LastModifiedById");
            CreateIndex("dbo.DeliveryPersons", "AddedById");
            CreateIndex("dbo.DeliveryPersons", "LastModifiedById");
            CreateIndex("dbo.CustomerShipAddresses", "AddedById");
            CreateIndex("dbo.CustomerShipAddresses", "LastModifiedById");
            CreateIndex("dbo.PurchaseOrders", "AddedById");
            CreateIndex("dbo.PurchaseOrders", "LastModifiedById");
            CreateIndex("dbo.PurchaseOrderClearances", "AddedById");
            CreateIndex("dbo.PurchaseOrderClearances", "LastModifiedById");
            CreateIndex("dbo.PurchaseOrderStatusHistories", "AddedById");
            CreateIndex("dbo.PurchaseOrderStatusHistories", "LastModifiedById");
            CreateIndex("dbo.PurchaseOrderLineItems", "AddedById");
            CreateIndex("dbo.PurchaseOrderLineItems", "LastModifiedById");
            CreateIndex("dbo.PurchaseOrderPayments", "AddedById");
            CreateIndex("dbo.PurchaseOrderPayments", "LastModifiedById");
            CreateIndex("dbo.MainProductGroups", "AddedById");
            CreateIndex("dbo.MainProductGroups", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestRules", "AddedById");
            CreateIndex("dbo.StockProductRequestRules", "LastModifiedById");
            CreateIndex("dbo.ProductTypes", "AddedById");
            CreateIndex("dbo.ProductTypes", "LastModifiedById");
            CreateIndex("dbo.StockProductRequests", "AddedById");
            CreateIndex("dbo.StockProductRequests", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestProducts", "AddedById");
            CreateIndex("dbo.StockProductRequestProducts", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestProductDetails", "AddedById");
            CreateIndex("dbo.StockProductRequestProductDetails", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestStatus", "AddedById");
            CreateIndex("dbo.StockProductRequestStatus", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestSupplyTypes", "AddedById");
            CreateIndex("dbo.StockProductRequestSupplyTypes", "LastModifiedById");
            CreateIndex("dbo.StockProducts", "AddedById");
            CreateIndex("dbo.StockProducts", "LastModifiedById");
            CreateIndex("dbo.FiscalYears", "AddedById");
            CreateIndex("dbo.FiscalYears", "LastModifiedById");
            CreateIndex("dbo.ReorderCalcTypes", "AddedById");
            CreateIndex("dbo.ReorderCalcTypes", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestTypes", "AddedById");
            CreateIndex("dbo.StockProductRequestTypes", "LastModifiedById");
            CreateIndex("dbo.StockTypes", "AddedById");
            CreateIndex("dbo.StockTypes", "LastModifiedById");
            CreateIndex("dbo.Suppliers", "AddedById");
            CreateIndex("dbo.Suppliers", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestRuleCalcTypes", "AddedById");
            CreateIndex("dbo.StockProductRequestRuleCalcTypes", "LastModifiedById");
            CreateIndex("dbo.StockProductRequestRuleTypes", "AddedById");
            CreateIndex("dbo.StockProductRequestRuleTypes", "LastModifiedById");
            CreateIndex("dbo.Manufactures", "AddedById");
            CreateIndex("dbo.Manufactures", "LastModifiedById");
            CreateIndex("dbo.ProductComments", "AddedById");
            CreateIndex("dbo.ProductComments", "LastModifiedById");
            CreateIndex("dbo.ProductGroups", "AddedById");
            CreateIndex("dbo.ProductGroups", "LastModifiedById");
            CreateIndex("dbo.ProductPictures", "AddedById");
            CreateIndex("dbo.ProductPictures", "LastModifiedById");
            CreateIndex("dbo.ProductRates", "AddedById");
            CreateIndex("dbo.ProductRates", "LastModifiedById");
            CreateIndex("dbo.ProductTagValues", "AddedById");
            CreateIndex("dbo.ProductTagValues", "LastModifiedById");
            CreateIndex("dbo.ProductTags", "AddedById");
            CreateIndex("dbo.ProductTags", "LastModifiedById");
            CreateIndex("dbo.StockHistoryOnHands", "AddedById");
            CreateIndex("dbo.StockHistoryOnHands", "LastModifiedById");
            CreateIndex("dbo.CustomerAreas", "AddedById");
            CreateIndex("dbo.CustomerAreas", "LastModifiedById");
            CreateIndex("dbo.RegionAreas", "AddedById");
            CreateIndex("dbo.RegionAreas", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityDayAreas", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityDayAreas", "LastModifiedById");
            CreateIndex("dbo.CompanyPersonnels", "AddedById");
            CreateIndex("dbo.CompanyPersonnels", "LastModifiedById");
            CreateIndex("dbo.CompanyOrgCharts", "AddedById");
            CreateIndex("dbo.CompanyOrgCharts", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityEvents", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityEvents", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityEventTypes", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityEventTypes", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityVisitTypes", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityPoints", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityPoints", "LastModifiedById");
            CreateIndex("dbo.RegionAreaLevelTypes", "AddedById");
            CreateIndex("dbo.RegionAreaLevelTypes", "LastModifiedById");
            CreateIndex("dbo.RegionAreaPoints", "AddedById");
            CreateIndex("dbo.RegionAreaPoints", "LastModifiedById");
            CreateIndex("dbo.Clearances", "AddedById");
            CreateIndex("dbo.Clearances", "LastModifiedById");
            CreateIndex("dbo.CompanyPersonnelRoutes", "AddedById");
            CreateIndex("dbo.CompanyPersonnelRoutes", "LastModifiedById");
            CreateIndex("dbo.DiscountCodes", "AddedById");
            CreateIndex("dbo.DiscountCodes", "LastModifiedById");
            CreateIndex("dbo.ItemImages", "AddedById");
            CreateIndex("dbo.ItemImages", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityCommentTypes", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedById");
            CreateIndex("dbo.PersonnelDailyActivityEventComments", "AddedById");
            CreateIndex("dbo.PersonnelDailyActivityEventComments", "LastModifiedById");
            CreateIndex("dbo.ProductSupplierGuarantees", "AddedById");
            CreateIndex("dbo.ProductSupplierGuarantees", "LastModifiedById");
            AddForeignKey("dbo.BankAccounts", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BankAccounts", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BaseTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BaseValues", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BaseValues", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BaseTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BasketItems", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Baskets", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BasketNotes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BasketNotes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Customers", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Companies", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyCenters", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Stocks", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Stocks", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockOnHandSyncs", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockOnHandSyncs", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockActiveOnHands", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockActiveOnHands", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Products", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CharValues", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CharTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CharGroups", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CharGroups", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CharTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CharValues", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrderLineItems", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrders", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CityRegions", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CityRegions", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Stores", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Stores", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreActions", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreActions", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreActiveOnhands", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreActiveOnhands", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreActivePriceLists", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreActivePriceLists", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreCalendars", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreCalendars", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreCalendarHistories", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CalendarTemplates", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CalendarTemplateHolidays", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CalendarTemplateHolidays", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CalendarTemplateOpenTimes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CalendarTemplateOpenTimes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CalendarTemplates", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreCalendarHistories", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreDeliveryPersons", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.DeliveryPersons", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.DeliveryPersons", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StoreDeliveryPersons", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CustomerShipAddresses", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CustomerShipAddresses", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrders", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrders", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderClearances", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderClearances", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderStatusHistories", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderStatusHistories", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderLineItems", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderLineItems", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderPayments", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PurchaseOrderPayments", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrders", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrderLineItems", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Products", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.MainProductGroups", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.MainProductGroups", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestRules", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestRules", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequests", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequests", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestProducts", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestProducts", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestProductDetails", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestProductDetails", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestStatus", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestStatus", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestSupplyTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestSupplyTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProducts", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.FiscalYears", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.FiscalYears", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProducts", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ReorderCalcTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ReorderCalcTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Suppliers", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Suppliers", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestRuleCalcTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestRuleCalcTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestRuleTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockProductRequestRuleTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Manufactures", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Manufactures", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductComments", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductComments", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductGroups", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductGroups", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductPictures", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductPictures", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductRates", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductRates", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductTagValues", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductTagValues", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductTags", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductTags", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockHistoryOnHands", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.StockHistoryOnHands", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyCenters", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Companies", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CustomerAreas", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CustomerAreas", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.RegionAreas", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.RegionAreas", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityDayAreas", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyPersonnels", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyOrgCharts", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyOrgCharts", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyPersonnels", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEvents", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEvents", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityVisitTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityPoints", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityPoints", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityDayAreas", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.RegionAreaLevelTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.RegionAreaLevelTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.RegionAreaPoints", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.RegionAreaPoints", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Customers", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Baskets", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.BasketItems", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Clearances", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.Clearances", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyPersonnelRoutes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.CompanyPersonnelRoutes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.DiscountCodes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.DiscountCodes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ItemImages", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ItemImages", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityCommentTypes", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventComments", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventComments", "LastModifiedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductSupplierGuarantees", "AddedById", "dbo.Principals", "Id");
            AddForeignKey("dbo.ProductSupplierGuarantees", "LastModifiedById", "dbo.Principals", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ProductSupplierGuarantees", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductSupplierGuarantees", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityEventComments", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityEventComments", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityCommentTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ItemImages", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ItemImages", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.DiscountCodes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.DiscountCodes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyPersonnelRoutes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyPersonnelRoutes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Clearances", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Clearances", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.BasketItems", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Baskets", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Customers", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.RegionAreaPoints", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.RegionAreaPoints", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.RegionAreaLevelTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.RegionAreaLevelTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityDayAreas", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityPoints", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityPoints", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityVisitTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityEventTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityEventTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityEvents", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityEvents", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyPersonnels", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyOrgCharts", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyOrgCharts", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyPersonnels", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PersonnelDailyActivityDayAreas", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.RegionAreas", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.RegionAreas", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CustomerAreas", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CustomerAreas", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Companies", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyCenters", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockHistoryOnHands", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockHistoryOnHands", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductTags", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductTags", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductTagValues", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductTagValues", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductRates", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductRates", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductPictures", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductPictures", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductGroups", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductGroups", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductComments", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductComments", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Manufactures", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Manufactures", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRuleTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRuleTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRuleCalcTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRuleCalcTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Suppliers", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Suppliers", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ReorderCalcTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ReorderCalcTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProducts", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.FiscalYears", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.FiscalYears", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProducts", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestSupplyTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestSupplyTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestStatus", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestStatus", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestProductDetails", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestProductDetails", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestProducts", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestProducts", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequests", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequests", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.ProductTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.ProductTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRules", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRules", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.MainProductGroups", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.MainProductGroups", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Products", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.IncompletePurchaseOrderLineItems", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.IncompletePurchaseOrders", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderPayments", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderPayments", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderLineItems", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderLineItems", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderStatusHistories", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderStatusHistories", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderClearances", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderClearances", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrders", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrders", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CustomerShipAddresses", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CustomerShipAddresses", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreDeliveryPersons", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.DeliveryPersons", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.DeliveryPersons", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreDeliveryPersons", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreCalendarHistories", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplates", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplateOpenTimes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplateOpenTimes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplateHolidays", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplateHolidays", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplates", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreCalendarHistories", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreCalendars", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StoreCalendars", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreActivePriceLists", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StoreActivePriceLists", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreActiveOnhands", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StoreActiveOnhands", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StoreActions", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StoreActions", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Stores", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Stores", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CityRegions", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CityRegions", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.IncompletePurchaseOrders", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.IncompletePurchaseOrderLineItems", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CharValues", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CharTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CharGroups", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.CharGroups", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CharTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CharValues", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Products", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockActiveOnHands", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockActiveOnHands", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.StockOnHandSyncs", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.StockOnHandSyncs", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Stocks", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.Stocks", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.CompanyCenters", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Companies", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Customers", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.BasketNotes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.BasketNotes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.Baskets", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.BasketItems", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.BaseTypes", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.BaseValues", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.BaseValues", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.BaseTypes", "AddedById", "dbo.Principals");
            DropForeignKey("dbo.BankAccounts", "LastModifiedById", "dbo.Principals");
            DropForeignKey("dbo.BankAccounts", "AddedById", "dbo.Principals");
            DropIndex("dbo.ProductSupplierGuarantees", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductSupplierGuarantees", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityEventComments", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityEventComments", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityCommentTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityCommentTypes", new[] { "AddedById" });
            DropIndex("dbo.ItemImages", new[] { "LastModifiedById" });
            DropIndex("dbo.ItemImages", new[] { "AddedById" });
            DropIndex("dbo.DiscountCodes", new[] { "LastModifiedById" });
            DropIndex("dbo.DiscountCodes", new[] { "AddedById" });
            DropIndex("dbo.CompanyPersonnelRoutes", new[] { "LastModifiedById" });
            DropIndex("dbo.CompanyPersonnelRoutes", new[] { "AddedById" });
            DropIndex("dbo.Clearances", new[] { "LastModifiedById" });
            DropIndex("dbo.Clearances", new[] { "AddedById" });
            DropIndex("dbo.RegionAreaPoints", new[] { "LastModifiedById" });
            DropIndex("dbo.RegionAreaPoints", new[] { "AddedById" });
            DropIndex("dbo.RegionAreaLevelTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.RegionAreaLevelTypes", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityPoints", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityPoints", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityVisitTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityVisitTypes", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityEventTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityEventTypes", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityEvents", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityEvents", new[] { "AddedById" });
            DropIndex("dbo.CompanyOrgCharts", new[] { "LastModifiedById" });
            DropIndex("dbo.CompanyOrgCharts", new[] { "AddedById" });
            DropIndex("dbo.CompanyPersonnels", new[] { "LastModifiedById" });
            DropIndex("dbo.CompanyPersonnels", new[] { "AddedById" });
            DropIndex("dbo.PersonnelDailyActivityDayAreas", new[] { "LastModifiedById" });
            DropIndex("dbo.PersonnelDailyActivityDayAreas", new[] { "AddedById" });
            DropIndex("dbo.RegionAreas", new[] { "LastModifiedById" });
            DropIndex("dbo.RegionAreas", new[] { "AddedById" });
            DropIndex("dbo.CustomerAreas", new[] { "LastModifiedById" });
            DropIndex("dbo.CustomerAreas", new[] { "AddedById" });
            DropIndex("dbo.StockHistoryOnHands", new[] { "LastModifiedById" });
            DropIndex("dbo.StockHistoryOnHands", new[] { "AddedById" });
            DropIndex("dbo.ProductTags", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductTags", new[] { "AddedById" });
            DropIndex("dbo.ProductTagValues", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductTagValues", new[] { "AddedById" });
            DropIndex("dbo.ProductRates", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductRates", new[] { "AddedById" });
            DropIndex("dbo.ProductPictures", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductPictures", new[] { "AddedById" });
            DropIndex("dbo.ProductGroups", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductGroups", new[] { "AddedById" });
            DropIndex("dbo.ProductComments", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductComments", new[] { "AddedById" });
            DropIndex("dbo.Manufactures", new[] { "LastModifiedById" });
            DropIndex("dbo.Manufactures", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestRuleTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestRuleTypes", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestRuleCalcTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestRuleCalcTypes", new[] { "AddedById" });
            DropIndex("dbo.Suppliers", new[] { "LastModifiedById" });
            DropIndex("dbo.Suppliers", new[] { "AddedById" });
            DropIndex("dbo.StockTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.StockTypes", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestTypes", new[] { "AddedById" });
            DropIndex("dbo.ReorderCalcTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.ReorderCalcTypes", new[] { "AddedById" });
            DropIndex("dbo.FiscalYears", new[] { "LastModifiedById" });
            DropIndex("dbo.FiscalYears", new[] { "AddedById" });
            DropIndex("dbo.StockProducts", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProducts", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestSupplyTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestSupplyTypes", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestStatus", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestStatus", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestProductDetails", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestProductDetails", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestProducts", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestProducts", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequests", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequests", new[] { "AddedById" });
            DropIndex("dbo.ProductTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.ProductTypes", new[] { "AddedById" });
            DropIndex("dbo.StockProductRequestRules", new[] { "LastModifiedById" });
            DropIndex("dbo.StockProductRequestRules", new[] { "AddedById" });
            DropIndex("dbo.MainProductGroups", new[] { "LastModifiedById" });
            DropIndex("dbo.MainProductGroups", new[] { "AddedById" });
            DropIndex("dbo.PurchaseOrderPayments", new[] { "LastModifiedById" });
            DropIndex("dbo.PurchaseOrderPayments", new[] { "AddedById" });
            DropIndex("dbo.PurchaseOrderLineItems", new[] { "LastModifiedById" });
            DropIndex("dbo.PurchaseOrderLineItems", new[] { "AddedById" });
            DropIndex("dbo.PurchaseOrderStatusHistories", new[] { "LastModifiedById" });
            DropIndex("dbo.PurchaseOrderStatusHistories", new[] { "AddedById" });
            DropIndex("dbo.PurchaseOrderClearances", new[] { "LastModifiedById" });
            DropIndex("dbo.PurchaseOrderClearances", new[] { "AddedById" });
            DropIndex("dbo.PurchaseOrders", new[] { "LastModifiedById" });
            DropIndex("dbo.PurchaseOrders", new[] { "AddedById" });
            DropIndex("dbo.CustomerShipAddresses", new[] { "LastModifiedById" });
            DropIndex("dbo.CustomerShipAddresses", new[] { "AddedById" });
            DropIndex("dbo.DeliveryPersons", new[] { "LastModifiedById" });
            DropIndex("dbo.DeliveryPersons", new[] { "AddedById" });
            DropIndex("dbo.StoreDeliveryPersons", new[] { "LastModifiedById" });
            DropIndex("dbo.StoreDeliveryPersons", new[] { "AddedById" });
            DropIndex("dbo.CalendarTemplateOpenTimes", new[] { "LastModifiedById" });
            DropIndex("dbo.CalendarTemplateOpenTimes", new[] { "AddedById" });
            DropIndex("dbo.CalendarTemplateHolidays", new[] { "LastModifiedById" });
            DropIndex("dbo.CalendarTemplateHolidays", new[] { "AddedById" });
            DropIndex("dbo.CalendarTemplates", new[] { "LastModifiedById" });
            DropIndex("dbo.CalendarTemplates", new[] { "AddedById" });
            DropIndex("dbo.StoreCalendarHistories", new[] { "LastModifiedById" });
            DropIndex("dbo.StoreCalendarHistories", new[] { "AddedById" });
            DropIndex("dbo.StoreCalendars", new[] { "LastModifiedById" });
            DropIndex("dbo.StoreCalendars", new[] { "AddedById" });
            DropIndex("dbo.StoreActivePriceLists", new[] { "LastModifiedById" });
            DropIndex("dbo.StoreActivePriceLists", new[] { "AddedById" });
            DropIndex("dbo.StoreActiveOnhands", new[] { "LastModifiedById" });
            DropIndex("dbo.StoreActiveOnhands", new[] { "AddedById" });
            DropIndex("dbo.StoreActions", new[] { "LastModifiedById" });
            DropIndex("dbo.StoreActions", new[] { "AddedById" });
            DropIndex("dbo.Stores", new[] { "LastModifiedById" });
            DropIndex("dbo.Stores", new[] { "AddedById" });
            DropIndex("dbo.CityRegions", new[] { "LastModifiedById" });
            DropIndex("dbo.CityRegions", new[] { "AddedById" });
            DropIndex("dbo.IncompletePurchaseOrders", new[] { "LastModifiedById" });
            DropIndex("dbo.IncompletePurchaseOrders", new[] { "AddedById" });
            DropIndex("dbo.IncompletePurchaseOrderLineItems", new[] { "LastModifiedById" });
            DropIndex("dbo.IncompletePurchaseOrderLineItems", new[] { "AddedById" });
            DropIndex("dbo.CharGroups", new[] { "LastModifiedById" });
            DropIndex("dbo.CharGroups", new[] { "AddedById" });
            DropIndex("dbo.CharTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.CharTypes", new[] { "AddedById" });
            DropIndex("dbo.CharValues", new[] { "LastModifiedById" });
            DropIndex("dbo.CharValues", new[] { "AddedById" });
            DropIndex("dbo.Products", new[] { "LastModifiedById" });
            DropIndex("dbo.Products", new[] { "AddedById" });
            DropIndex("dbo.StockActiveOnHands", new[] { "LastModifiedById" });
            DropIndex("dbo.StockActiveOnHands", new[] { "AddedById" });
            DropIndex("dbo.StockOnHandSyncs", new[] { "LastModifiedById" });
            DropIndex("dbo.StockOnHandSyncs", new[] { "AddedById" });
            DropIndex("dbo.Stocks", new[] { "LastModifiedById" });
            DropIndex("dbo.Stocks", new[] { "AddedById" });
            DropIndex("dbo.CompanyCenters", new[] { "LastModifiedById" });
            DropIndex("dbo.CompanyCenters", new[] { "AddedById" });
            DropIndex("dbo.Companies", new[] { "LastModifiedById" });
            DropIndex("dbo.Companies", new[] { "AddedById" });
            DropIndex("dbo.Customers", new[] { "LastModifiedById" });
            DropIndex("dbo.Customers", new[] { "AddedById" });
            DropIndex("dbo.BasketNotes", new[] { "LastModifiedById" });
            DropIndex("dbo.BasketNotes", new[] { "AddedById" });
            DropIndex("dbo.Baskets", new[] { "LastModifiedById" });
            DropIndex("dbo.Baskets", new[] { "AddedById" });
            DropIndex("dbo.BasketItems", new[] { "LastModifiedById" });
            DropIndex("dbo.BasketItems", new[] { "AddedById" });
            DropIndex("dbo.BaseValues", new[] { "LastModifiedById" });
            DropIndex("dbo.BaseValues", new[] { "AddedById" });
            DropIndex("dbo.BaseTypes", new[] { "LastModifiedById" });
            DropIndex("dbo.BaseTypes", new[] { "AddedById" });
            DropIndex("dbo.BankAccounts", new[] { "LastModifiedById" });
            DropIndex("dbo.BankAccounts", new[] { "AddedById" });
            DropColumn("dbo.ProductSupplierGuarantees", "LastModifiedById");
            DropColumn("dbo.ProductSupplierGuarantees", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityEventComments", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityEventComments", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityCommentTypes", "AddedById");
            DropColumn("dbo.ItemImages", "LastModifiedById");
            DropColumn("dbo.ItemImages", "AddedById");
            DropColumn("dbo.DiscountCodes", "LastModifiedById");
            DropColumn("dbo.DiscountCodes", "AddedById");
            DropColumn("dbo.CompanyPersonnelRoutes", "LastModifiedById");
            DropColumn("dbo.CompanyPersonnelRoutes", "AddedById");
            DropColumn("dbo.Clearances", "LastModifiedById");
            DropColumn("dbo.Clearances", "AddedById");
            DropColumn("dbo.RegionAreaPoints", "LastModifiedById");
            DropColumn("dbo.RegionAreaPoints", "AddedById");
            DropColumn("dbo.RegionAreaLevelTypes", "LastModifiedById");
            DropColumn("dbo.RegionAreaLevelTypes", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityPoints", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityPoints", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityVisitTypes", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityEventTypes", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityEventTypes", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityEvents", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityEvents", "AddedById");
            DropColumn("dbo.CompanyOrgCharts", "LastModifiedById");
            DropColumn("dbo.CompanyOrgCharts", "AddedById");
            DropColumn("dbo.CompanyPersonnels", "LastModifiedById");
            DropColumn("dbo.CompanyPersonnels", "AddedById");
            DropColumn("dbo.PersonnelDailyActivityDayAreas", "LastModifiedById");
            DropColumn("dbo.PersonnelDailyActivityDayAreas", "AddedById");
            DropColumn("dbo.RegionAreas", "LastModifiedById");
            DropColumn("dbo.RegionAreas", "AddedById");
            DropColumn("dbo.CustomerAreas", "LastModifiedById");
            DropColumn("dbo.CustomerAreas", "AddedById");
            DropColumn("dbo.StockHistoryOnHands", "LastModifiedById");
            DropColumn("dbo.StockHistoryOnHands", "AddedById");
            DropColumn("dbo.ProductTags", "LastModifiedById");
            DropColumn("dbo.ProductTags", "AddedById");
            DropColumn("dbo.ProductTagValues", "LastModifiedById");
            DropColumn("dbo.ProductTagValues", "AddedById");
            DropColumn("dbo.ProductRates", "LastModifiedById");
            DropColumn("dbo.ProductRates", "AddedById");
            DropColumn("dbo.ProductPictures", "LastModifiedById");
            DropColumn("dbo.ProductPictures", "AddedById");
            DropColumn("dbo.ProductGroups", "LastModifiedById");
            DropColumn("dbo.ProductGroups", "AddedById");
            DropColumn("dbo.ProductComments", "LastModifiedById");
            DropColumn("dbo.ProductComments", "AddedById");
            DropColumn("dbo.Manufactures", "LastModifiedById");
            DropColumn("dbo.Manufactures", "AddedById");
            DropColumn("dbo.StockProductRequestRuleTypes", "LastModifiedById");
            DropColumn("dbo.StockProductRequestRuleTypes", "AddedById");
            DropColumn("dbo.StockProductRequestRuleCalcTypes", "LastModifiedById");
            DropColumn("dbo.StockProductRequestRuleCalcTypes", "AddedById");
            DropColumn("dbo.Suppliers", "LastModifiedById");
            DropColumn("dbo.Suppliers", "AddedById");
            DropColumn("dbo.StockTypes", "LastModifiedById");
            DropColumn("dbo.StockTypes", "AddedById");
            DropColumn("dbo.StockProductRequestTypes", "LastModifiedById");
            DropColumn("dbo.StockProductRequestTypes", "AddedById");
            DropColumn("dbo.ReorderCalcTypes", "LastModifiedById");
            DropColumn("dbo.ReorderCalcTypes", "AddedById");
            DropColumn("dbo.FiscalYears", "LastModifiedById");
            DropColumn("dbo.FiscalYears", "AddedById");
            DropColumn("dbo.StockProducts", "LastModifiedById");
            DropColumn("dbo.StockProducts", "AddedById");
            DropColumn("dbo.StockProductRequestSupplyTypes", "LastModifiedById");
            DropColumn("dbo.StockProductRequestSupplyTypes", "AddedById");
            DropColumn("dbo.StockProductRequestStatus", "LastModifiedById");
            DropColumn("dbo.StockProductRequestStatus", "AddedById");
            DropColumn("dbo.StockProductRequestProductDetails", "LastModifiedById");
            DropColumn("dbo.StockProductRequestProductDetails", "AddedById");
            DropColumn("dbo.StockProductRequestProducts", "LastModifiedById");
            DropColumn("dbo.StockProductRequestProducts", "AddedById");
            DropColumn("dbo.StockProductRequests", "LastModifiedById");
            DropColumn("dbo.StockProductRequests", "AddedById");
            DropColumn("dbo.ProductTypes", "LastModifiedById");
            DropColumn("dbo.ProductTypes", "AddedById");
            DropColumn("dbo.StockProductRequestRules", "LastModifiedById");
            DropColumn("dbo.StockProductRequestRules", "AddedById");
            DropColumn("dbo.MainProductGroups", "LastModifiedById");
            DropColumn("dbo.MainProductGroups", "AddedById");
            DropColumn("dbo.PurchaseOrderPayments", "LastModifiedById");
            DropColumn("dbo.PurchaseOrderPayments", "AddedById");
            DropColumn("dbo.PurchaseOrderLineItems", "LastModifiedById");
            DropColumn("dbo.PurchaseOrderLineItems", "AddedById");
            DropColumn("dbo.PurchaseOrderStatusHistories", "LastModifiedById");
            DropColumn("dbo.PurchaseOrderStatusHistories", "AddedById");
            DropColumn("dbo.PurchaseOrderClearances", "LastModifiedById");
            DropColumn("dbo.PurchaseOrderClearances", "AddedById");
            DropColumn("dbo.PurchaseOrders", "LastModifiedById");
            DropColumn("dbo.PurchaseOrders", "AddedById");
            DropColumn("dbo.CustomerShipAddresses", "LastModifiedById");
            DropColumn("dbo.CustomerShipAddresses", "AddedById");
            DropColumn("dbo.DeliveryPersons", "LastModifiedById");
            DropColumn("dbo.DeliveryPersons", "AddedById");
            DropColumn("dbo.StoreDeliveryPersons", "LastModifiedById");
            DropColumn("dbo.StoreDeliveryPersons", "AddedById");
            DropColumn("dbo.CalendarTemplateOpenTimes", "LastModifiedById");
            DropColumn("dbo.CalendarTemplateOpenTimes", "AddedById");
            DropColumn("dbo.CalendarTemplateHolidays", "LastModifiedById");
            DropColumn("dbo.CalendarTemplateHolidays", "AddedById");
            DropColumn("dbo.CalendarTemplates", "LastModifiedById");
            DropColumn("dbo.CalendarTemplates", "AddedById");
            DropColumn("dbo.StoreCalendarHistories", "LastModifiedById");
            DropColumn("dbo.StoreCalendarHistories", "AddedById");
            DropColumn("dbo.StoreCalendars", "LastModifiedById");
            DropColumn("dbo.StoreCalendars", "AddedById");
            DropColumn("dbo.StoreActivePriceLists", "LastModifiedById");
            DropColumn("dbo.StoreActivePriceLists", "AddedById");
            DropColumn("dbo.StoreActiveOnhands", "LastModifiedById");
            DropColumn("dbo.StoreActiveOnhands", "AddedById");
            DropColumn("dbo.StoreActions", "LastModifiedById");
            DropColumn("dbo.StoreActions", "AddedById");
            DropColumn("dbo.Stores", "LastModifiedById");
            DropColumn("dbo.Stores", "AddedById");
            DropColumn("dbo.CityRegions", "LastModifiedById");
            DropColumn("dbo.CityRegions", "AddedById");
            DropColumn("dbo.IncompletePurchaseOrders", "LastModifiedById");
            DropColumn("dbo.IncompletePurchaseOrders", "AddedById");
            DropColumn("dbo.IncompletePurchaseOrderLineItems", "LastModifiedById");
            DropColumn("dbo.IncompletePurchaseOrderLineItems", "AddedById");
            DropColumn("dbo.CharGroups", "LastModifiedById");
            DropColumn("dbo.CharGroups", "AddedById");
            DropColumn("dbo.CharTypes", "LastModifiedById");
            DropColumn("dbo.CharTypes", "AddedById");
            DropColumn("dbo.CharValues", "LastModifiedById");
            DropColumn("dbo.CharValues", "AddedById");
            DropColumn("dbo.Products", "LastModifiedById");
            DropColumn("dbo.Products", "AddedById");
            DropColumn("dbo.StockActiveOnHands", "LastModifiedById");
            DropColumn("dbo.StockActiveOnHands", "AddedById");
            DropColumn("dbo.StockOnHandSyncs", "LastModifiedById");
            DropColumn("dbo.StockOnHandSyncs", "AddedById");
            DropColumn("dbo.Stocks", "LastModifiedById");
            DropColumn("dbo.Stocks", "AddedById");
            DropColumn("dbo.CompanyCenters", "LastModifiedById");
            DropColumn("dbo.CompanyCenters", "AddedById");
            DropColumn("dbo.Companies", "LastModifiedById");
            DropColumn("dbo.Companies", "AddedById");
            DropColumn("dbo.Customers", "LastModifiedById");
            DropColumn("dbo.Customers", "AddedById");
            DropColumn("dbo.BasketNotes", "LastModifiedById");
            DropColumn("dbo.BasketNotes", "AddedById");
            DropColumn("dbo.Baskets", "LastModifiedById");
            DropColumn("dbo.Baskets", "AddedById");
            DropColumn("dbo.BasketItems", "LastModifiedById");
            DropColumn("dbo.BasketItems", "AddedById");
            DropColumn("dbo.BaseValues", "LastModifiedById");
            DropColumn("dbo.BaseValues", "AddedById");
            DropColumn("dbo.BaseTypes", "LastModifiedById");
            DropColumn("dbo.BaseTypes", "AddedById");
            DropColumn("dbo.BankAccounts", "LastModifiedById");
            DropColumn("dbo.BankAccounts", "AddedById");
        }
    }
}
