namespace Anatoli.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CascasdeDelete3 : DbMigration
    {
        public override void Up()
        {
            CreateIndex("dbo.BankAccounts", "PrivateLabelOwner_Id");
            CreateIndex("dbo.PrincipalPermissions", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Permissions", "PrivateLabelOwner_Id");
            CreateIndex("dbo.BaseTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.BaseValues", "PrivateLabelOwner_Id");
            CreateIndex("dbo.BasketItems", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Baskets", "PrivateLabelOwner_Id");
            CreateIndex("dbo.BasketNotes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Customers", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CustomerShipAddresses", "PrivateLabelOwner_Id");
            CreateIndex("dbo.IncompletePurchaseOrders", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CityRegions", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Stores", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StoreActions", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StoreActiveOnhands", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Products", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CharValues", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CharTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CharGroups", "PrivateLabelOwner_Id");
            CreateIndex("dbo.IncompletePurchaseOrderLineItems", "PrivateLabelOwner_Id");
            CreateIndex("dbo.MainProductGroups", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequestRules", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ProductTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequests", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ReorderCalcTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProducts", "PrivateLabelOwner_Id");
            CreateIndex("dbo.FiscalYears", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Stocks", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockOnHandSyncs", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockActiveOnHands", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockHistoryOnHands", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequestProducts", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequestProductDetails", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequestStatus", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequestTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Suppliers", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StockProductRequestRuleTypes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Manufactures", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ProductComments", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ProductGroups", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ProductPictures", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ProductRates", "PrivateLabelOwner_Id");
            CreateIndex("dbo.PurchaseOrderLineItems", "PrivateLabelOwner_Id");
            CreateIndex("dbo.PurchaseOrders", "PrivateLabelOwner_Id");
            CreateIndex("dbo.PurchaseOrderClearances", "PrivateLabelOwner_Id");
            CreateIndex("dbo.PurchaseOrderHistories", "PrivateLabelOwner_Id");
            CreateIndex("dbo.PurchaseOrderPayments", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StoreActivePriceLists", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StoreCalendars", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StoreCalendarHistories", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CalendarTemplates", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CalendarTemplateHolidays", "PrivateLabelOwner_Id");
            CreateIndex("dbo.CalendarTemplateOpenTimes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.StoreDeliveryPersons", "PrivateLabelOwner_Id");
            CreateIndex("dbo.DeliveryPersons", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Clearances", "PrivateLabelOwner_Id");
            CreateIndex("dbo.DiscountCodes", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Groups", "PrivateLabelOwner_Id");
            CreateIndex("dbo.Roles", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ItemImages", "PrivateLabelOwner_Id");
            CreateIndex("dbo.ProductSupplierGuarantees", "PrivateLabelOwner_Id");
            AddForeignKey("dbo.Permissions", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PrincipalPermissions", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.BankAccounts", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.BaseValues", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.BaseTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.BasketNotes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CustomerShipAddresses", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CityRegions", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Stores", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StoreActions", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StoreActiveOnhands", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CharGroups", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CharTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CharValues", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.IncompletePurchaseOrderLineItems", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.MainProductGroups", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequestRules", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ProductTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequests", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ReorderCalcTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.FiscalYears", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProducts", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Stocks", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockOnHandSyncs", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockActiveOnHands", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockHistoryOnHands", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequestProducts", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequestProductDetails", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequestStatus", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequestTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Suppliers", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StockProductRequestRuleTypes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Manufactures", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Products", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ProductComments", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ProductGroups", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ProductPictures", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ProductRates", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PurchaseOrderLineItems", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PurchaseOrders", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PurchaseOrderClearances", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PurchaseOrderHistories", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.PurchaseOrderPayments", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StoreActivePriceLists", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StoreCalendars", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CalendarTemplateHolidays", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CalendarTemplateOpenTimes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.CalendarTemplates", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StoreCalendarHistories", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.DeliveryPersons", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StoreDeliveryPersons", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.IncompletePurchaseOrders", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Customers", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Baskets", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.BasketItems", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Clearances", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.DiscountCodes", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Groups", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Roles", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ItemImages", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
            AddForeignKey("dbo.ProductSupplierGuarantees", "PrivateLabelOwner_Id", "dbo.Principals", "Id", cascadeDelete: false);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ProductSupplierGuarantees", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ItemImages", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Roles", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Groups", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.DiscountCodes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Clearances", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.BasketItems", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Baskets", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Customers", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.IncompletePurchaseOrders", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StoreDeliveryPersons", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.DeliveryPersons", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StoreCalendarHistories", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplates", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplateOpenTimes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CalendarTemplateHolidays", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StoreCalendars", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StoreActivePriceLists", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderPayments", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderHistories", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderClearances", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrders", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.PurchaseOrderLineItems", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ProductRates", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ProductPictures", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ProductGroups", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ProductComments", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Products", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Manufactures", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRuleTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Suppliers", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestStatus", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestProductDetails", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestProducts", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockHistoryOnHands", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockActiveOnHands", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockOnHandSyncs", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Stocks", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProducts", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.FiscalYears", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ReorderCalcTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequests", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.ProductTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StockProductRequestRules", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.MainProductGroups", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.IncompletePurchaseOrderLineItems", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CharValues", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CharTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CharGroups", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StoreActiveOnhands", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.StoreActions", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Stores", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CityRegions", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.CustomerShipAddresses", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.BasketNotes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.BaseTypes", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.BaseValues", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.BankAccounts", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.PrincipalPermissions", "PrivateLabelOwner_Id", "dbo.Principals");
            DropForeignKey("dbo.Permissions", "PrivateLabelOwner_Id", "dbo.Principals");
            DropIndex("dbo.ProductSupplierGuarantees", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ItemImages", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Roles", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Groups", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.DiscountCodes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Clearances", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.DeliveryPersons", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StoreDeliveryPersons", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CalendarTemplateOpenTimes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CalendarTemplateHolidays", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CalendarTemplates", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StoreCalendarHistories", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StoreCalendars", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StoreActivePriceLists", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.PurchaseOrderPayments", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.PurchaseOrderHistories", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.PurchaseOrderClearances", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.PurchaseOrders", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.PurchaseOrderLineItems", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ProductRates", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ProductPictures", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ProductGroups", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ProductComments", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Manufactures", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequestRuleTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Suppliers", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequestTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequestStatus", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequestProductDetails", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequestProducts", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockHistoryOnHands", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockActiveOnHands", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockOnHandSyncs", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Stocks", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.FiscalYears", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProducts", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ReorderCalcTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequests", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.ProductTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StockProductRequestRules", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.MainProductGroups", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.IncompletePurchaseOrderLineItems", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CharGroups", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CharTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CharValues", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Products", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StoreActiveOnhands", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.StoreActions", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Stores", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CityRegions", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.IncompletePurchaseOrders", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.CustomerShipAddresses", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Customers", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.BasketNotes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Baskets", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.BasketItems", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.BaseValues", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.BaseTypes", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.Permissions", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.PrincipalPermissions", new[] { "PrivateLabelOwner_Id" });
            DropIndex("dbo.BankAccounts", new[] { "PrivateLabelOwner_Id" });
        }
    }
}
