// <auto-generated />
namespace Anatoli.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PermissionMigration5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PermissionMigration5));
        
        string IMigrationMetadata.Id
        {
            get { return "201604030946277_Permission-Migration-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
