// <auto-generated />
namespace Anatoli.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StockRequest17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockRequest17));
        
        string IMigrationMetadata.Id
        {
            get { return "201601082322473_Stock-Request-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
