namespace Anatoli.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PermissionMigration1 : DbMigration
    {
        public override void Up()
        {
            Sql("alter table dbo.CompanyPersonnelRoutes drop constraint [FK_dbo.VisitorRoutes_dbo.Users_AddedBy_Id]");
            Sql("alter table dbo.CompanyPersonnelRoutes drop constraint [FK_dbo.VisitorRoutes_dbo.Users_LastModifiedBy_Id]");
            Sql("alter table dbo.RegionAreaLevelTypes drop constraint [FK_dbo.DistCompanyRegionLevelTypes_dbo.Users_AddedBy_Id]");
            Sql("alter table dbo.RegionAreaLevelTypes drop constraint [FK_dbo.DistCompanyRegionLevelTypes_dbo.Users_LastModifiedBy_Id]");
            Sql("alter table dbo.CompanyCenters drop constraint [FK_dbo.DistCompanyCenters_dbo.Users_AddedBy_Id]");
            Sql("alter table dbo.CompanyCenters drop constraint [FK_dbo.DistCompanyCenters_dbo.Users_LastModifiedBy_Id]");
            Sql("alter table dbo.CompanyPersonnels drop constraint [FK_dbo.Visitors_dbo.Users_AddedBy_Id]");
            Sql("alter table dbo.CompanyPersonnels drop constraint [FK_dbo.Visitors_dbo.Users_LastModifiedBy_Id]");

            DropForeignKey("dbo.Stocks", "Accept1ById", "dbo.Users");
            DropForeignKey("dbo.Stocks", "Accept2ById", "dbo.Users");
            DropForeignKey("dbo.Stocks", "Accept3ById", "dbo.Users");

            DropForeignKey("dbo.PrincipalPermissions", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PrincipalPermissions", "ApplicationOwnerId", "dbo.ApplicationOwners");
            DropForeignKey("dbo.PrincipalPermissions", "DataOwnerId", "dbo.DataOwners");
            DropForeignKey("dbo.PrincipalPermissions", "DataOwnerCenterId", "dbo.DataOwnerCenters");
            DropForeignKey("dbo.PrincipalPermissions", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Permissions", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Permissions", "ApplicationOwnerId", "dbo.ApplicationOwners");
            DropForeignKey("dbo.Permissions", "DataOwnerId", "dbo.DataOwners");
            DropForeignKey("dbo.Permissions", "DataOwnerCenterId", "dbo.DataOwnerCenters");
            DropForeignKey("dbo.Permissions", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Permissions", "Parent_Id", "dbo.Permissions");
            DropForeignKey("dbo.PrincipalPermissions", "UserId", "dbo.Users");
            DropForeignKey("dbo.Stocks", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Companies", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyCenters", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyCenters", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Customers", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CustomerAreas", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CustomerAreas", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.RegionAreas", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.RegionAreas", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityDayAreas", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyPersonnels", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyOrgCharts", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyOrgCharts", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyPersonnels", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityEvents", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityEvents", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityEventTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityEventTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityVisitTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityPoints", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityPoints", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityDayAreas", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.RegionAreaLevelTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.RegionAreaLevelTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.RegionAreaPoints", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.RegionAreaPoints", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Baskets", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BasketItems", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BasketItems", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Products", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CharValues", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CharTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CharGroups", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CharGroups", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CharTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CharValues", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.IncompletePurchaseOrderLineItems", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.IncompletePurchaseOrders", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CityRegions", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CityRegions", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Stores", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Stores", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreActions", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreActions", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreActiveOnhands", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreActiveOnhands", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreActivePriceLists", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreActivePriceLists", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreCalendars", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreCalendars", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreCalendarHistories", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CalendarTemplates", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CalendarTemplateHolidays", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CalendarTemplateHolidays", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CalendarTemplateOpenTimes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CalendarTemplateOpenTimes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CalendarTemplates", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreCalendarHistories", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreDeliveryPersons", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.DeliveryPersons", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.DeliveryPersons", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StoreDeliveryPersons", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CustomerShipAddresses", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CustomerShipAddresses", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrders", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrders", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderClearances", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderClearances", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderStatusHistories", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderStatusHistories", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderLineItems", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderLineItems", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderPayments", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PurchaseOrderPayments", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.IncompletePurchaseOrders", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.IncompletePurchaseOrderLineItems", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Products", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.MainProductGroups", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.MainProductGroups", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestRules", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestRules", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequests", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequests", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockOnHandSyncs", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockOnHandSyncs", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockActiveOnHands", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockActiveOnHands", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockHistoryOnHands", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockHistoryOnHands", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestProducts", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestProducts", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestProductDetails", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestProductDetails", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestStatus", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestStatus", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestSupplyTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestSupplyTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProducts", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.FiscalYears", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.FiscalYears", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProducts", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ReorderCalcTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ReorderCalcTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Suppliers", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Suppliers", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestRuleCalcTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestRuleCalcTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestRuleTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.StockProductRequestRuleTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Manufactures", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Manufactures", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductComments", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductComments", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductGroups", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductGroups", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductPictures", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductPictures", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductRates", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductRates", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductTagValues", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductTagValues", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductTags", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductTags", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BasketNotes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BasketNotes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Baskets", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Customers", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Companies", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Stocks", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.UsersStocks", "UserId", "dbo.Users");
            DropForeignKey("dbo.UsersStocks", "StockID", "dbo.Stocks");
            DropForeignKey("dbo.BankAccounts", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BankAccounts", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BaseTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BaseValues", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BaseValues", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.BaseTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Clearances", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Clearances", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyPersonnelRoutes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.CompanyPersonnelRoutes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.DiscountCodes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.DiscountCodes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Groups", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Groups", "ApplicationOwnerId", "dbo.ApplicationOwners");
            DropForeignKey("dbo.Groups", "DataOwnerId", "dbo.DataOwners");
            DropForeignKey("dbo.Groups", "DataOwnerCenterId", "dbo.DataOwnerCenters");
            DropForeignKey("dbo.Groups", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.Groups", "Principal_Id", "dbo.ApplicationOwners");
            DropForeignKey("dbo.Users", "Group_Id", "dbo.Groups");
            DropForeignKey("dbo.ItemImages", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ItemImages", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityCommentTypes", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityEventComments", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.PersonnelDailyActivityEventComments", "LastModifiedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductSupplierGuarantees", "AddedBy_Id", "dbo.Users");
            DropForeignKey("dbo.ProductSupplierGuarantees", "LastModifiedBy_Id", "dbo.Users");
            DropIndex("dbo.Users", new[] { "Group_Id" });
            DropIndex("dbo.PrincipalPermissions", new[] { "UserId" });
            DropIndex("dbo.PrincipalPermissions", new[] { "ApplicationOwnerId" });
            DropIndex("dbo.PrincipalPermissions", new[] { "DataOwnerId" });
            DropIndex("dbo.PrincipalPermissions", new[] { "DataOwnerCenterId" });
            DropIndex("dbo.PrincipalPermissions", new[] { "AddedBy_Id" });
            DropIndex("dbo.PrincipalPermissions", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Permissions", new[] { "ApplicationOwnerId" });
            DropIndex("dbo.Permissions", new[] { "DataOwnerId" });
            DropIndex("dbo.Permissions", new[] { "DataOwnerCenterId" });
            DropIndex("dbo.Permissions", new[] { "AddedBy_Id" });
            DropIndex("dbo.Permissions", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Permissions", new[] { "Parent_Id" });
            DropIndex("dbo.Stocks", new[] { "Accept1ById" });
            DropIndex("dbo.Stocks", new[] { "Accept2ById" });
            DropIndex("dbo.Stocks", new[] { "Accept3ById" });
            DropIndex("dbo.Stocks", new[] { "AddedBy_Id" });
            DropIndex("dbo.Stocks", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Companies", new[] { "AddedBy_Id" });
            DropIndex("dbo.Companies", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CompanyCenters", new[] { "AddedBy_Id" });
            DropIndex("dbo.CompanyCenters", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Customers", new[] { "AddedBy_Id" });
            DropIndex("dbo.Customers", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CustomerAreas", new[] { "AddedBy_Id" });
            DropIndex("dbo.CustomerAreas", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.RegionAreas", new[] { "AddedBy_Id" });
            DropIndex("dbo.RegionAreas", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityDayAreas", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityDayAreas", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CompanyPersonnels", new[] { "AddedBy_Id" });
            DropIndex("dbo.CompanyPersonnels", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CompanyOrgCharts", new[] { "AddedBy_Id" });
            DropIndex("dbo.CompanyOrgCharts", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityEvents", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityEvents", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityEventTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityEventTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityVisitTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityVisitTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityPoints", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityPoints", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.RegionAreaLevelTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.RegionAreaLevelTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.RegionAreaPoints", new[] { "AddedBy_Id" });
            DropIndex("dbo.RegionAreaPoints", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Baskets", new[] { "AddedBy_Id" });
            DropIndex("dbo.Baskets", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.BasketItems", new[] { "AddedBy_Id" });
            DropIndex("dbo.BasketItems", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Products", new[] { "AddedBy_Id" });
            DropIndex("dbo.Products", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CharValues", new[] { "AddedBy_Id" });
            DropIndex("dbo.CharValues", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CharTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.CharTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CharGroups", new[] { "AddedBy_Id" });
            DropIndex("dbo.CharGroups", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.IncompletePurchaseOrderLineItems", new[] { "AddedBy_Id" });
            DropIndex("dbo.IncompletePurchaseOrderLineItems", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.IncompletePurchaseOrders", new[] { "AddedBy_Id" });
            DropIndex("dbo.IncompletePurchaseOrders", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CityRegions", new[] { "AddedBy_Id" });
            DropIndex("dbo.CityRegions", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Stores", new[] { "AddedBy_Id" });
            DropIndex("dbo.Stores", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StoreActions", new[] { "AddedBy_Id" });
            DropIndex("dbo.StoreActions", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StoreActiveOnhands", new[] { "AddedBy_Id" });
            DropIndex("dbo.StoreActiveOnhands", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StoreActivePriceLists", new[] { "AddedBy_Id" });
            DropIndex("dbo.StoreActivePriceLists", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StoreCalendars", new[] { "AddedBy_Id" });
            DropIndex("dbo.StoreCalendars", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StoreCalendarHistories", new[] { "AddedBy_Id" });
            DropIndex("dbo.StoreCalendarHistories", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CalendarTemplates", new[] { "AddedBy_Id" });
            DropIndex("dbo.CalendarTemplates", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CalendarTemplateHolidays", new[] { "AddedBy_Id" });
            DropIndex("dbo.CalendarTemplateHolidays", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CalendarTemplateOpenTimes", new[] { "AddedBy_Id" });
            DropIndex("dbo.CalendarTemplateOpenTimes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StoreDeliveryPersons", new[] { "AddedBy_Id" });
            DropIndex("dbo.StoreDeliveryPersons", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.DeliveryPersons", new[] { "AddedBy_Id" });
            DropIndex("dbo.DeliveryPersons", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CustomerShipAddresses", new[] { "AddedBy_Id" });
            DropIndex("dbo.CustomerShipAddresses", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PurchaseOrders", new[] { "AddedBy_Id" });
            DropIndex("dbo.PurchaseOrders", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PurchaseOrderClearances", new[] { "AddedBy_Id" });
            DropIndex("dbo.PurchaseOrderClearances", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PurchaseOrderStatusHistories", new[] { "AddedBy_Id" });
            DropIndex("dbo.PurchaseOrderStatusHistories", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PurchaseOrderLineItems", new[] { "AddedBy_Id" });
            DropIndex("dbo.PurchaseOrderLineItems", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PurchaseOrderPayments", new[] { "AddedBy_Id" });
            DropIndex("dbo.PurchaseOrderPayments", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.MainProductGroups", new[] { "AddedBy_Id" });
            DropIndex("dbo.MainProductGroups", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestRules", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestRules", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequests", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequests", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockOnHandSyncs", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockOnHandSyncs", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockActiveOnHands", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockActiveOnHands", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockHistoryOnHands", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockHistoryOnHands", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestProducts", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestProducts", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestProductDetails", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestProductDetails", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestStatus", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestStatus", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestSupplyTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestSupplyTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProducts", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProducts", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.FiscalYears", new[] { "AddedBy_Id" });
            DropIndex("dbo.FiscalYears", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ReorderCalcTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.ReorderCalcTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Suppliers", new[] { "AddedBy_Id" });
            DropIndex("dbo.Suppliers", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestRuleCalcTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestRuleCalcTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.StockProductRequestRuleTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.StockProductRequestRuleTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Manufactures", new[] { "AddedBy_Id" });
            DropIndex("dbo.Manufactures", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductComments", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductComments", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductGroups", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductGroups", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductPictures", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductPictures", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductRates", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductRates", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductTagValues", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductTagValues", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductTags", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductTags", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.BasketNotes", new[] { "AddedBy_Id" });
            DropIndex("dbo.BasketNotes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.BankAccounts", new[] { "AddedBy_Id" });
            DropIndex("dbo.BankAccounts", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.BaseTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.BaseTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.BaseValues", new[] { "AddedBy_Id" });
            DropIndex("dbo.BaseValues", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Clearances", new[] { "AddedBy_Id" });
            DropIndex("dbo.Clearances", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.CompanyPersonnelRoutes", new[] { "AddedBy_Id" });
            DropIndex("dbo.CompanyPersonnelRoutes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.DiscountCodes", new[] { "AddedBy_Id" });
            DropIndex("dbo.DiscountCodes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Groups", new[] { "ApplicationOwnerId" });
            DropIndex("dbo.Groups", new[] { "DataOwnerId" });
            DropIndex("dbo.Groups", new[] { "DataOwnerCenterId" });
            DropIndex("dbo.Groups", new[] { "AddedBy_Id" });
            DropIndex("dbo.Groups", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.Groups", new[] { "Principal_Id" });
            DropIndex("dbo.ItemImages", new[] { "AddedBy_Id" });
            DropIndex("dbo.ItemImages", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityCommentTypes", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityCommentTypes", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityEventComments", new[] { "AddedBy_Id" });
            DropIndex("dbo.PersonnelDailyActivityEventComments", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.ProductSupplierGuarantees", new[] { "AddedBy_Id" });
            DropIndex("dbo.ProductSupplierGuarantees", new[] { "LastModifiedBy_Id" });
            DropIndex("dbo.UsersStocks", new[] { "UserId" });
            DropIndex("dbo.UsersStocks", new[] { "StockID" });
            CreateTable(
                "dbo.ApplicationModules",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Name = c.String(),
                        ApplicationId = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Applications", t => t.ApplicationId, cascadeDelete: true)
                .Index(t => t.ApplicationId);
            
            CreateTable(
                "dbo.ApplicationModuleResources",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Name = c.String(),
                        ApplicationModuleId = c.Guid(nullable: false),
                        ParentId = c.Guid(),
                        NodeId = c.Int(nullable: false),
                        NLeft = c.Int(nullable: false),
                        NRight = c.Int(nullable: false),
                        NLevel = c.Int(nullable: false),
                        Priority = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.ApplicationModules", t => t.ApplicationModuleId, cascadeDelete: true)
                .ForeignKey("dbo.ApplicationModuleResources", t => t.ParentId)
                .Index(t => t.ApplicationModuleId)
                .Index(t => t.ParentId);
            
            CreateTable(
                "dbo.PermissionActions",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Name = c.String(),
                        ParentId = c.Guid(),
                        NodeId = c.Int(nullable: false),
                        NLeft = c.Int(nullable: false),
                        NRight = c.Int(nullable: false),
                        NLevel = c.Int(nullable: false),
                        Priority = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.PermissionActions", t => t.ParentId)
                .Index(t => t.ParentId);
            
            CreateTable(
                "dbo.Principals",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Title = c.String(maxLength: 200),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.PrincipalGroups",
                c => new
                    {
                        GroupId = c.Guid(nullable: false),
                        PrincipalID = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => new { t.GroupId, t.PrincipalID })
                .ForeignKey("dbo.Groups", t => t.GroupId, cascadeDelete: true)
                .ForeignKey("dbo.Principals", t => t.PrincipalID, cascadeDelete: true)
                .Index(t => t.GroupId)
                .Index(t => t.PrincipalID);
            
            AddColumn("dbo.PrincipalPermissions", "PrincipalId", c => c.Guid(nullable: false));
            AddColumn("dbo.Permissions", "Name", c => c.String());
            AddColumn("dbo.Permissions", "ApplicationModuleResourceId", c => c.Guid(nullable: false));
            AddColumn("dbo.Permissions", "PermissionActionId", c => c.Guid(nullable: false));
            AddColumn("dbo.Groups", "ParentId", c => c.Guid());
            AddColumn("dbo.Groups", "NodeId", c => c.Int(nullable: false));
            AddColumn("dbo.Groups", "NLeft", c => c.Int(nullable: false));
            AddColumn("dbo.Groups", "NRight", c => c.Int(nullable: false));
            AddColumn("dbo.Groups", "NLevel", c => c.Int(nullable: false));
            AddColumn("dbo.Groups", "Priority", c => c.Int());
            AlterColumn("dbo.PrincipalPermissions", "Grant", c => c.Int(nullable: false));
            AlterColumn("dbo.Stocks", "Accept1ById", c => c.Guid());
            AlterColumn("dbo.Stocks", "Accept2ById", c => c.Guid());
            AlterColumn("dbo.Stocks", "Accept3ById", c => c.Guid());
            AlterColumn("dbo.Groups", "Name", c => c.String(maxLength: 200));
            CreateIndex("dbo.Permissions", "ApplicationModuleResourceId");
            CreateIndex("dbo.Permissions", "PermissionActionId");
            CreateIndex("dbo.PrincipalPermissions", "PrincipalId");
            CreateIndex("dbo.Groups", "ParentId");
            CreateIndex("dbo.Stocks", "Accept1ById");
            CreateIndex("dbo.Stocks", "Accept2ById");
            CreateIndex("dbo.Stocks", "Accept3ById");
            AddForeignKey("dbo.Permissions", "ApplicationModuleResourceId", "dbo.ApplicationModuleResources", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Permissions", "PermissionActionId", "dbo.PermissionActions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Groups", "ParentId", "dbo.Groups", "Id");
            AddForeignKey("dbo.PrincipalPermissions", "PrincipalId", "dbo.Principals", "Id");
            DropColumn("dbo.Users", "Group_Id");
            DropColumn("dbo.PrincipalPermissions", "UserId");
            DropColumn("dbo.PrincipalPermissions", "Number_ID");
            DropColumn("dbo.PrincipalPermissions", "CreatedDate");
            DropColumn("dbo.PrincipalPermissions", "LastUpdate");
            DropColumn("dbo.PrincipalPermissions", "IsRemoved");
            DropColumn("dbo.PrincipalPermissions", "ApplicationOwnerId");
            DropColumn("dbo.PrincipalPermissions", "DataOwnerId");
            DropColumn("dbo.PrincipalPermissions", "DataOwnerCenterId");
            DropColumn("dbo.PrincipalPermissions", "AddedBy_Id");
            DropColumn("dbo.PrincipalPermissions", "LastModifiedBy_Id");
            DropColumn("dbo.Permissions", "PersianTitle");
            DropColumn("dbo.Permissions", "Resource");
            DropColumn("dbo.Permissions", "Action");
            DropColumn("dbo.Permissions", "Number_ID");
            DropColumn("dbo.Permissions", "CreatedDate");
            DropColumn("dbo.Permissions", "LastUpdate");
            DropColumn("dbo.Permissions", "IsRemoved");
            DropColumn("dbo.Permissions", "ApplicationOwnerId");
            DropColumn("dbo.Permissions", "DataOwnerId");
            DropColumn("dbo.Permissions", "DataOwnerCenterId");
            DropColumn("dbo.Permissions", "AddedBy_Id");
            DropColumn("dbo.Permissions", "LastModifiedBy_Id");
            DropColumn("dbo.Permissions", "Parent_Id");
            DropColumn("dbo.Stocks", "AddedBy_Id");
            DropColumn("dbo.Stocks", "LastModifiedBy_Id");
            DropColumn("dbo.Companies", "AddedBy_Id");
            DropColumn("dbo.Companies", "LastModifiedBy_Id");
            DropColumn("dbo.CompanyCenters", "AddedBy_Id");
            DropColumn("dbo.CompanyCenters", "LastModifiedBy_Id");
            DropColumn("dbo.Customers", "AddedBy_Id");
            DropColumn("dbo.Customers", "LastModifiedBy_Id");
            DropColumn("dbo.CustomerAreas", "AddedBy_Id");
            DropColumn("dbo.CustomerAreas", "LastModifiedBy_Id");
            DropColumn("dbo.RegionAreas", "AddedBy_Id");
            DropColumn("dbo.RegionAreas", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityDayAreas", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityDayAreas", "LastModifiedBy_Id");
            DropColumn("dbo.CompanyPersonnels", "AddedBy_Id");
            DropColumn("dbo.CompanyPersonnels", "LastModifiedBy_Id");
            DropColumn("dbo.CompanyOrgCharts", "AddedBy_Id");
            DropColumn("dbo.CompanyOrgCharts", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityEvents", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityEvents", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityEventTypes", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityEventTypes", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityVisitTypes", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityPoints", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityPoints", "LastModifiedBy_Id");
            DropColumn("dbo.RegionAreaLevelTypes", "AddedBy_Id");
            DropColumn("dbo.RegionAreaLevelTypes", "LastModifiedBy_Id");
            DropColumn("dbo.RegionAreaPoints", "AddedBy_Id");
            DropColumn("dbo.RegionAreaPoints", "LastModifiedBy_Id");
            DropColumn("dbo.Baskets", "AddedBy_Id");
            DropColumn("dbo.Baskets", "LastModifiedBy_Id");
            DropColumn("dbo.BasketItems", "AddedBy_Id");
            DropColumn("dbo.BasketItems", "LastModifiedBy_Id");
            DropColumn("dbo.Products", "AddedBy_Id");
            DropColumn("dbo.Products", "LastModifiedBy_Id");
            DropColumn("dbo.CharValues", "AddedBy_Id");
            DropColumn("dbo.CharValues", "LastModifiedBy_Id");
            DropColumn("dbo.CharTypes", "AddedBy_Id");
            DropColumn("dbo.CharTypes", "LastModifiedBy_Id");
            DropColumn("dbo.CharGroups", "AddedBy_Id");
            DropColumn("dbo.CharGroups", "LastModifiedBy_Id");
            DropColumn("dbo.IncompletePurchaseOrderLineItems", "AddedBy_Id");
            DropColumn("dbo.IncompletePurchaseOrderLineItems", "LastModifiedBy_Id");
            DropColumn("dbo.IncompletePurchaseOrders", "AddedBy_Id");
            DropColumn("dbo.IncompletePurchaseOrders", "LastModifiedBy_Id");
            DropColumn("dbo.CityRegions", "AddedBy_Id");
            DropColumn("dbo.CityRegions", "LastModifiedBy_Id");
            DropColumn("dbo.Stores", "AddedBy_Id");
            DropColumn("dbo.Stores", "LastModifiedBy_Id");
            DropColumn("dbo.StoreActions", "AddedBy_Id");
            DropColumn("dbo.StoreActions", "LastModifiedBy_Id");
            DropColumn("dbo.StoreActiveOnhands", "AddedBy_Id");
            DropColumn("dbo.StoreActiveOnhands", "LastModifiedBy_Id");
            DropColumn("dbo.StoreActivePriceLists", "AddedBy_Id");
            DropColumn("dbo.StoreActivePriceLists", "LastModifiedBy_Id");
            DropColumn("dbo.StoreCalendars", "AddedBy_Id");
            DropColumn("dbo.StoreCalendars", "LastModifiedBy_Id");
            DropColumn("dbo.StoreCalendarHistories", "AddedBy_Id");
            DropColumn("dbo.StoreCalendarHistories", "LastModifiedBy_Id");
            DropColumn("dbo.CalendarTemplates", "AddedBy_Id");
            DropColumn("dbo.CalendarTemplates", "LastModifiedBy_Id");
            DropColumn("dbo.CalendarTemplateHolidays", "AddedBy_Id");
            DropColumn("dbo.CalendarTemplateHolidays", "LastModifiedBy_Id");
            DropColumn("dbo.CalendarTemplateOpenTimes", "AddedBy_Id");
            DropColumn("dbo.CalendarTemplateOpenTimes", "LastModifiedBy_Id");
            DropColumn("dbo.StoreDeliveryPersons", "AddedBy_Id");
            DropColumn("dbo.StoreDeliveryPersons", "LastModifiedBy_Id");
            DropColumn("dbo.DeliveryPersons", "AddedBy_Id");
            DropColumn("dbo.DeliveryPersons", "LastModifiedBy_Id");
            DropColumn("dbo.CustomerShipAddresses", "AddedBy_Id");
            DropColumn("dbo.CustomerShipAddresses", "LastModifiedBy_Id");
            DropColumn("dbo.PurchaseOrders", "AddedBy_Id");
            DropColumn("dbo.PurchaseOrders", "LastModifiedBy_Id");
            DropColumn("dbo.PurchaseOrderClearances", "AddedBy_Id");
            DropColumn("dbo.PurchaseOrderClearances", "LastModifiedBy_Id");
            DropColumn("dbo.PurchaseOrderStatusHistories", "AddedBy_Id");
            DropColumn("dbo.PurchaseOrderStatusHistories", "LastModifiedBy_Id");
            DropColumn("dbo.PurchaseOrderLineItems", "AddedBy_Id");
            DropColumn("dbo.PurchaseOrderLineItems", "LastModifiedBy_Id");
            DropColumn("dbo.PurchaseOrderPayments", "AddedBy_Id");
            DropColumn("dbo.PurchaseOrderPayments", "LastModifiedBy_Id");
            DropColumn("dbo.MainProductGroups", "AddedBy_Id");
            DropColumn("dbo.MainProductGroups", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestRules", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestRules", "LastModifiedBy_Id");
            DropColumn("dbo.ProductTypes", "AddedBy_Id");
            DropColumn("dbo.ProductTypes", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequests", "AddedBy_Id");
            DropColumn("dbo.StockProductRequests", "LastModifiedBy_Id");
            DropColumn("dbo.StockOnHandSyncs", "AddedBy_Id");
            DropColumn("dbo.StockOnHandSyncs", "LastModifiedBy_Id");
            DropColumn("dbo.StockActiveOnHands", "AddedBy_Id");
            DropColumn("dbo.StockActiveOnHands", "LastModifiedBy_Id");
            DropColumn("dbo.StockHistoryOnHands", "AddedBy_Id");
            DropColumn("dbo.StockHistoryOnHands", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestProducts", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestProducts", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestProductDetails", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestProductDetails", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestStatus", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestStatus", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestSupplyTypes", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestSupplyTypes", "LastModifiedBy_Id");
            DropColumn("dbo.StockProducts", "AddedBy_Id");
            DropColumn("dbo.StockProducts", "LastModifiedBy_Id");
            DropColumn("dbo.FiscalYears", "AddedBy_Id");
            DropColumn("dbo.FiscalYears", "LastModifiedBy_Id");
            DropColumn("dbo.ReorderCalcTypes", "AddedBy_Id");
            DropColumn("dbo.ReorderCalcTypes", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestTypes", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestTypes", "LastModifiedBy_Id");
            DropColumn("dbo.StockTypes", "AddedBy_Id");
            DropColumn("dbo.StockTypes", "LastModifiedBy_Id");
            DropColumn("dbo.Suppliers", "AddedBy_Id");
            DropColumn("dbo.Suppliers", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestRuleCalcTypes", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestRuleCalcTypes", "LastModifiedBy_Id");
            DropColumn("dbo.StockProductRequestRuleTypes", "AddedBy_Id");
            DropColumn("dbo.StockProductRequestRuleTypes", "LastModifiedBy_Id");
            DropColumn("dbo.Manufactures", "AddedBy_Id");
            DropColumn("dbo.Manufactures", "LastModifiedBy_Id");
            DropColumn("dbo.ProductComments", "AddedBy_Id");
            DropColumn("dbo.ProductComments", "LastModifiedBy_Id");
            DropColumn("dbo.ProductGroups", "AddedBy_Id");
            DropColumn("dbo.ProductGroups", "LastModifiedBy_Id");
            DropColumn("dbo.ProductPictures", "AddedBy_Id");
            DropColumn("dbo.ProductPictures", "LastModifiedBy_Id");
            DropColumn("dbo.ProductRates", "AddedBy_Id");
            DropColumn("dbo.ProductRates", "LastModifiedBy_Id");
            DropColumn("dbo.ProductTagValues", "AddedBy_Id");
            DropColumn("dbo.ProductTagValues", "LastModifiedBy_Id");
            DropColumn("dbo.ProductTags", "AddedBy_Id");
            DropColumn("dbo.ProductTags", "LastModifiedBy_Id");
            DropColumn("dbo.BasketNotes", "AddedBy_Id");
            DropColumn("dbo.BasketNotes", "LastModifiedBy_Id");
            DropColumn("dbo.BankAccounts", "AddedBy_Id");
            DropColumn("dbo.BankAccounts", "LastModifiedBy_Id");
            DropColumn("dbo.BaseTypes", "AddedBy_Id");
            DropColumn("dbo.BaseTypes", "LastModifiedBy_Id");
            DropColumn("dbo.BaseValues", "AddedBy_Id");
            DropColumn("dbo.BaseValues", "LastModifiedBy_Id");
            DropColumn("dbo.Clearances", "AddedBy_Id");
            DropColumn("dbo.Clearances", "LastModifiedBy_Id");
            DropColumn("dbo.CompanyPersonnelRoutes", "AddedBy_Id");
            DropColumn("dbo.CompanyPersonnelRoutes", "LastModifiedBy_Id");
            DropColumn("dbo.DiscountCodes", "AddedBy_Id");
            DropColumn("dbo.DiscountCodes", "LastModifiedBy_Id");
            DropColumn("dbo.Groups", "Number_ID");
            DropColumn("dbo.Groups", "CreatedDate");
            DropColumn("dbo.Groups", "LastUpdate");
            DropColumn("dbo.Groups", "IsRemoved");
            DropColumn("dbo.Groups", "ApplicationOwnerId");
            DropColumn("dbo.Groups", "DataOwnerId");
            DropColumn("dbo.Groups", "DataOwnerCenterId");
            DropColumn("dbo.Groups", "AddedBy_Id");
            DropColumn("dbo.Groups", "LastModifiedBy_Id");
            DropColumn("dbo.Groups", "Principal_Id");
            DropColumn("dbo.ItemImages", "AddedBy_Id");
            DropColumn("dbo.ItemImages", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityCommentTypes", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityEventComments", "AddedBy_Id");
            DropColumn("dbo.PersonnelDailyActivityEventComments", "LastModifiedBy_Id");
            DropColumn("dbo.ProductSupplierGuarantees", "AddedBy_Id");
            DropColumn("dbo.ProductSupplierGuarantees", "LastModifiedBy_Id");
            DropTable("dbo.UsersStocks");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.UsersStocks",
                c => new
                    {
                        UserId = c.String(nullable: false, maxLength: 128),
                        StockID = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => new { t.UserId, t.StockID });
            
            AddColumn("dbo.ProductSupplierGuarantees", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductSupplierGuarantees", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityEventComments", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityEventComments", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityCommentTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ItemImages", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ItemImages", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Groups", "Principal_Id", c => c.Guid(nullable: false));
            AddColumn("dbo.Groups", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Groups", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Groups", "DataOwnerCenterId", c => c.Guid(nullable: false));
            AddColumn("dbo.Groups", "DataOwnerId", c => c.Guid(nullable: false));
            AddColumn("dbo.Groups", "ApplicationOwnerId", c => c.Guid(nullable: false));
            AddColumn("dbo.Groups", "IsRemoved", c => c.Boolean(nullable: false));
            AddColumn("dbo.Groups", "LastUpdate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Groups", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Groups", "Number_ID", c => c.Int(nullable: false));
            AddColumn("dbo.DiscountCodes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.DiscountCodes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyPersonnelRoutes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyPersonnelRoutes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Clearances", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Clearances", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BaseValues", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BaseValues", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BaseTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BaseTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BankAccounts", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BankAccounts", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BasketNotes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BasketNotes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductTags", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductTags", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductTagValues", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductTagValues", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductRates", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductRates", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductPictures", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductPictures", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductGroups", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductGroups", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductComments", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductComments", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Manufactures", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Manufactures", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestRuleTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestRuleTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestRuleCalcTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestRuleCalcTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Suppliers", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Suppliers", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ReorderCalcTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ReorderCalcTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.FiscalYears", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.FiscalYears", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProducts", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProducts", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestSupplyTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestSupplyTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestStatus", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestStatus", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestProductDetails", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestProductDetails", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestProducts", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestProducts", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockHistoryOnHands", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockHistoryOnHands", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockActiveOnHands", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockActiveOnHands", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockOnHandSyncs", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockOnHandSyncs", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequests", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequests", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.ProductTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestRules", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StockProductRequestRules", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.MainProductGroups", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.MainProductGroups", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderPayments", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderPayments", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderLineItems", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderLineItems", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderStatusHistories", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderStatusHistories", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderClearances", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrderClearances", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrders", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PurchaseOrders", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CustomerShipAddresses", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CustomerShipAddresses", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.DeliveryPersons", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.DeliveryPersons", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreDeliveryPersons", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreDeliveryPersons", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CalendarTemplateOpenTimes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CalendarTemplateOpenTimes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CalendarTemplateHolidays", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CalendarTemplateHolidays", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CalendarTemplates", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CalendarTemplates", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreCalendarHistories", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreCalendarHistories", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreCalendars", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreCalendars", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreActivePriceLists", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreActivePriceLists", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreActiveOnhands", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreActiveOnhands", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreActions", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.StoreActions", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Stores", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Stores", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CityRegions", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CityRegions", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.IncompletePurchaseOrders", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.IncompletePurchaseOrders", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.IncompletePurchaseOrderLineItems", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.IncompletePurchaseOrderLineItems", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CharGroups", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CharGroups", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CharTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CharTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CharValues", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CharValues", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Products", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Products", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BasketItems", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.BasketItems", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Baskets", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Baskets", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RegionAreaPoints", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RegionAreaPoints", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RegionAreaLevelTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RegionAreaLevelTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityPoints", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityPoints", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityVisitTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityEventTypes", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityEventTypes", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityEvents", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityEvents", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyOrgCharts", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyOrgCharts", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyPersonnels", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyPersonnels", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityDayAreas", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PersonnelDailyActivityDayAreas", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RegionAreas", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RegionAreas", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CustomerAreas", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CustomerAreas", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Customers", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Customers", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyCenters", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.CompanyCenters", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Companies", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Companies", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Stocks", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Stocks", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Permissions", "Parent_Id", c => c.Guid());
            AddColumn("dbo.Permissions", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Permissions", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Permissions", "DataOwnerCenterId", c => c.Guid(nullable: false));
            AddColumn("dbo.Permissions", "DataOwnerId", c => c.Guid(nullable: false));
            AddColumn("dbo.Permissions", "ApplicationOwnerId", c => c.Guid(nullable: false));
            AddColumn("dbo.Permissions", "IsRemoved", c => c.Boolean(nullable: false));
            AddColumn("dbo.Permissions", "LastUpdate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Permissions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Permissions", "Number_ID", c => c.Int(nullable: false));
            AddColumn("dbo.Permissions", "Action", c => c.String());
            AddColumn("dbo.Permissions", "Resource", c => c.String());
            AddColumn("dbo.Permissions", "PersianTitle", c => c.String());
            AddColumn("dbo.PrincipalPermissions", "LastModifiedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PrincipalPermissions", "AddedBy_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.PrincipalPermissions", "DataOwnerCenterId", c => c.Guid(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "DataOwnerId", c => c.Guid(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "ApplicationOwnerId", c => c.Guid(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "IsRemoved", c => c.Boolean(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "LastUpdate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "Number_ID", c => c.Int(nullable: false));
            AddColumn("dbo.PrincipalPermissions", "UserId", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.Users", "Group_Id", c => c.Guid());
            DropForeignKey("dbo.PrincipalPermissions", "PrincipalId", "dbo.Principals");
            DropForeignKey("dbo.PrincipalGroups", "PrincipalID", "dbo.Principals");
            DropForeignKey("dbo.PrincipalGroups", "GroupId", "dbo.Groups");
            DropForeignKey("dbo.Groups", "ParentId", "dbo.Groups");
            DropForeignKey("dbo.Permissions", "PermissionActionId", "dbo.PermissionActions");
            DropForeignKey("dbo.PermissionActions", "ParentId", "dbo.PermissionActions");
            DropForeignKey("dbo.Permissions", "ApplicationModuleResourceId", "dbo.ApplicationModuleResources");
            DropForeignKey("dbo.ApplicationModuleResources", "ParentId", "dbo.ApplicationModuleResources");
            DropForeignKey("dbo.ApplicationModuleResources", "ApplicationModuleId", "dbo.ApplicationModules");
            DropForeignKey("dbo.ApplicationModules", "ApplicationId", "dbo.Applications");
            DropIndex("dbo.PrincipalGroups", new[] { "PrincipalID" });
            DropIndex("dbo.PrincipalGroups", new[] { "GroupId" });
            DropIndex("dbo.Stocks", new[] { "Accept3ById" });
            DropIndex("dbo.Stocks", new[] { "Accept2ById" });
            DropIndex("dbo.Stocks", new[] { "Accept1ById" });
            DropIndex("dbo.Groups", new[] { "ParentId" });
            DropIndex("dbo.PrincipalPermissions", new[] { "PrincipalId" });
            DropIndex("dbo.PermissionActions", new[] { "ParentId" });
            DropIndex("dbo.Permissions", new[] { "PermissionActionId" });
            DropIndex("dbo.Permissions", new[] { "ApplicationModuleResourceId" });
            DropIndex("dbo.ApplicationModuleResources", new[] { "ParentId" });
            DropIndex("dbo.ApplicationModuleResources", new[] { "ApplicationModuleId" });
            DropIndex("dbo.ApplicationModules", new[] { "ApplicationId" });
            AlterColumn("dbo.Groups", "Name", c => c.String());
            AlterColumn("dbo.Stocks", "Accept3ById", c => c.String(maxLength: 128));
            AlterColumn("dbo.Stocks", "Accept2ById", c => c.String(maxLength: 128));
            AlterColumn("dbo.Stocks", "Accept1ById", c => c.String(maxLength: 128));
            AlterColumn("dbo.PrincipalPermissions", "Grant", c => c.Boolean(nullable: false));
            DropColumn("dbo.Groups", "Priority");
            DropColumn("dbo.Groups", "NLevel");
            DropColumn("dbo.Groups", "NRight");
            DropColumn("dbo.Groups", "NLeft");
            DropColumn("dbo.Groups", "NodeId");
            DropColumn("dbo.Groups", "ParentId");
            DropColumn("dbo.Permissions", "PermissionActionId");
            DropColumn("dbo.Permissions", "ApplicationModuleResourceId");
            DropColumn("dbo.Permissions", "Name");
            DropColumn("dbo.PrincipalPermissions", "PrincipalId");
            DropTable("dbo.PrincipalGroups");
            DropTable("dbo.Principals");
            DropTable("dbo.PermissionActions");
            DropTable("dbo.ApplicationModuleResources");
            DropTable("dbo.ApplicationModules");
            CreateIndex("dbo.UsersStocks", "StockID");
            CreateIndex("dbo.UsersStocks", "UserId");
            CreateIndex("dbo.ProductSupplierGuarantees", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductSupplierGuarantees", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityEventComments", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityEventComments", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityCommentTypes", "AddedBy_Id");
            CreateIndex("dbo.ItemImages", "LastModifiedBy_Id");
            CreateIndex("dbo.ItemImages", "AddedBy_Id");
            CreateIndex("dbo.Groups", "Principal_Id");
            CreateIndex("dbo.Groups", "LastModifiedBy_Id");
            CreateIndex("dbo.Groups", "AddedBy_Id");
            CreateIndex("dbo.Groups", "DataOwnerCenterId");
            CreateIndex("dbo.Groups", "DataOwnerId");
            CreateIndex("dbo.Groups", "ApplicationOwnerId");
            CreateIndex("dbo.DiscountCodes", "LastModifiedBy_Id");
            CreateIndex("dbo.DiscountCodes", "AddedBy_Id");
            CreateIndex("dbo.CompanyPersonnelRoutes", "LastModifiedBy_Id");
            CreateIndex("dbo.CompanyPersonnelRoutes", "AddedBy_Id");
            CreateIndex("dbo.Clearances", "LastModifiedBy_Id");
            CreateIndex("dbo.Clearances", "AddedBy_Id");
            CreateIndex("dbo.BaseValues", "LastModifiedBy_Id");
            CreateIndex("dbo.BaseValues", "AddedBy_Id");
            CreateIndex("dbo.BaseTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.BaseTypes", "AddedBy_Id");
            CreateIndex("dbo.BankAccounts", "LastModifiedBy_Id");
            CreateIndex("dbo.BankAccounts", "AddedBy_Id");
            CreateIndex("dbo.BasketNotes", "LastModifiedBy_Id");
            CreateIndex("dbo.BasketNotes", "AddedBy_Id");
            CreateIndex("dbo.ProductTags", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductTags", "AddedBy_Id");
            CreateIndex("dbo.ProductTagValues", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductTagValues", "AddedBy_Id");
            CreateIndex("dbo.ProductRates", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductRates", "AddedBy_Id");
            CreateIndex("dbo.ProductPictures", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductPictures", "AddedBy_Id");
            CreateIndex("dbo.ProductGroups", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductGroups", "AddedBy_Id");
            CreateIndex("dbo.ProductComments", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductComments", "AddedBy_Id");
            CreateIndex("dbo.Manufactures", "LastModifiedBy_Id");
            CreateIndex("dbo.Manufactures", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestRuleTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestRuleTypes", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestRuleCalcTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestRuleCalcTypes", "AddedBy_Id");
            CreateIndex("dbo.Suppliers", "LastModifiedBy_Id");
            CreateIndex("dbo.Suppliers", "AddedBy_Id");
            CreateIndex("dbo.StockTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.StockTypes", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestTypes", "AddedBy_Id");
            CreateIndex("dbo.ReorderCalcTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.ReorderCalcTypes", "AddedBy_Id");
            CreateIndex("dbo.FiscalYears", "LastModifiedBy_Id");
            CreateIndex("dbo.FiscalYears", "AddedBy_Id");
            CreateIndex("dbo.StockProducts", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProducts", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestSupplyTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestSupplyTypes", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestStatus", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestStatus", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestProductDetails", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestProductDetails", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestProducts", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestProducts", "AddedBy_Id");
            CreateIndex("dbo.StockHistoryOnHands", "LastModifiedBy_Id");
            CreateIndex("dbo.StockHistoryOnHands", "AddedBy_Id");
            CreateIndex("dbo.StockActiveOnHands", "LastModifiedBy_Id");
            CreateIndex("dbo.StockActiveOnHands", "AddedBy_Id");
            CreateIndex("dbo.StockOnHandSyncs", "LastModifiedBy_Id");
            CreateIndex("dbo.StockOnHandSyncs", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequests", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequests", "AddedBy_Id");
            CreateIndex("dbo.ProductTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.ProductTypes", "AddedBy_Id");
            CreateIndex("dbo.StockProductRequestRules", "LastModifiedBy_Id");
            CreateIndex("dbo.StockProductRequestRules", "AddedBy_Id");
            CreateIndex("dbo.MainProductGroups", "LastModifiedBy_Id");
            CreateIndex("dbo.MainProductGroups", "AddedBy_Id");
            CreateIndex("dbo.PurchaseOrderPayments", "LastModifiedBy_Id");
            CreateIndex("dbo.PurchaseOrderPayments", "AddedBy_Id");
            CreateIndex("dbo.PurchaseOrderLineItems", "LastModifiedBy_Id");
            CreateIndex("dbo.PurchaseOrderLineItems", "AddedBy_Id");
            CreateIndex("dbo.PurchaseOrderStatusHistories", "LastModifiedBy_Id");
            CreateIndex("dbo.PurchaseOrderStatusHistories", "AddedBy_Id");
            CreateIndex("dbo.PurchaseOrderClearances", "LastModifiedBy_Id");
            CreateIndex("dbo.PurchaseOrderClearances", "AddedBy_Id");
            CreateIndex("dbo.PurchaseOrders", "LastModifiedBy_Id");
            CreateIndex("dbo.PurchaseOrders", "AddedBy_Id");
            CreateIndex("dbo.CustomerShipAddresses", "LastModifiedBy_Id");
            CreateIndex("dbo.CustomerShipAddresses", "AddedBy_Id");
            CreateIndex("dbo.DeliveryPersons", "LastModifiedBy_Id");
            CreateIndex("dbo.DeliveryPersons", "AddedBy_Id");
            CreateIndex("dbo.StoreDeliveryPersons", "LastModifiedBy_Id");
            CreateIndex("dbo.StoreDeliveryPersons", "AddedBy_Id");
            CreateIndex("dbo.CalendarTemplateOpenTimes", "LastModifiedBy_Id");
            CreateIndex("dbo.CalendarTemplateOpenTimes", "AddedBy_Id");
            CreateIndex("dbo.CalendarTemplateHolidays", "LastModifiedBy_Id");
            CreateIndex("dbo.CalendarTemplateHolidays", "AddedBy_Id");
            CreateIndex("dbo.CalendarTemplates", "LastModifiedBy_Id");
            CreateIndex("dbo.CalendarTemplates", "AddedBy_Id");
            CreateIndex("dbo.StoreCalendarHistories", "LastModifiedBy_Id");
            CreateIndex("dbo.StoreCalendarHistories", "AddedBy_Id");
            CreateIndex("dbo.StoreCalendars", "LastModifiedBy_Id");
            CreateIndex("dbo.StoreCalendars", "AddedBy_Id");
            CreateIndex("dbo.StoreActivePriceLists", "LastModifiedBy_Id");
            CreateIndex("dbo.StoreActivePriceLists", "AddedBy_Id");
            CreateIndex("dbo.StoreActiveOnhands", "LastModifiedBy_Id");
            CreateIndex("dbo.StoreActiveOnhands", "AddedBy_Id");
            CreateIndex("dbo.StoreActions", "LastModifiedBy_Id");
            CreateIndex("dbo.StoreActions", "AddedBy_Id");
            CreateIndex("dbo.Stores", "LastModifiedBy_Id");
            CreateIndex("dbo.Stores", "AddedBy_Id");
            CreateIndex("dbo.CityRegions", "LastModifiedBy_Id");
            CreateIndex("dbo.CityRegions", "AddedBy_Id");
            CreateIndex("dbo.IncompletePurchaseOrders", "LastModifiedBy_Id");
            CreateIndex("dbo.IncompletePurchaseOrders", "AddedBy_Id");
            CreateIndex("dbo.IncompletePurchaseOrderLineItems", "LastModifiedBy_Id");
            CreateIndex("dbo.IncompletePurchaseOrderLineItems", "AddedBy_Id");
            CreateIndex("dbo.CharGroups", "LastModifiedBy_Id");
            CreateIndex("dbo.CharGroups", "AddedBy_Id");
            CreateIndex("dbo.CharTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.CharTypes", "AddedBy_Id");
            CreateIndex("dbo.CharValues", "LastModifiedBy_Id");
            CreateIndex("dbo.CharValues", "AddedBy_Id");
            CreateIndex("dbo.Products", "LastModifiedBy_Id");
            CreateIndex("dbo.Products", "AddedBy_Id");
            CreateIndex("dbo.BasketItems", "LastModifiedBy_Id");
            CreateIndex("dbo.BasketItems", "AddedBy_Id");
            CreateIndex("dbo.Baskets", "LastModifiedBy_Id");
            CreateIndex("dbo.Baskets", "AddedBy_Id");
            CreateIndex("dbo.RegionAreaPoints", "LastModifiedBy_Id");
            CreateIndex("dbo.RegionAreaPoints", "AddedBy_Id");
            CreateIndex("dbo.RegionAreaLevelTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.RegionAreaLevelTypes", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityPoints", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityPoints", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityVisitTypes", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityEventTypes", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityEventTypes", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityEvents", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityEvents", "AddedBy_Id");
            CreateIndex("dbo.CompanyOrgCharts", "LastModifiedBy_Id");
            CreateIndex("dbo.CompanyOrgCharts", "AddedBy_Id");
            CreateIndex("dbo.CompanyPersonnels", "LastModifiedBy_Id");
            CreateIndex("dbo.CompanyPersonnels", "AddedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityDayAreas", "LastModifiedBy_Id");
            CreateIndex("dbo.PersonnelDailyActivityDayAreas", "AddedBy_Id");
            CreateIndex("dbo.RegionAreas", "LastModifiedBy_Id");
            CreateIndex("dbo.RegionAreas", "AddedBy_Id");
            CreateIndex("dbo.CustomerAreas", "LastModifiedBy_Id");
            CreateIndex("dbo.CustomerAreas", "AddedBy_Id");
            CreateIndex("dbo.Customers", "LastModifiedBy_Id");
            CreateIndex("dbo.Customers", "AddedBy_Id");
            CreateIndex("dbo.CompanyCenters", "LastModifiedBy_Id");
            CreateIndex("dbo.CompanyCenters", "AddedBy_Id");
            CreateIndex("dbo.Companies", "LastModifiedBy_Id");
            CreateIndex("dbo.Companies", "AddedBy_Id");
            CreateIndex("dbo.Stocks", "LastModifiedBy_Id");
            CreateIndex("dbo.Stocks", "AddedBy_Id");
            CreateIndex("dbo.Stocks", "Accept3ById");
            CreateIndex("dbo.Stocks", "Accept2ById");
            CreateIndex("dbo.Stocks", "Accept1ById");
            CreateIndex("dbo.Permissions", "Parent_Id");
            CreateIndex("dbo.Permissions", "LastModifiedBy_Id");
            CreateIndex("dbo.Permissions", "AddedBy_Id");
            CreateIndex("dbo.Permissions", "DataOwnerCenterId");
            CreateIndex("dbo.Permissions", "DataOwnerId");
            CreateIndex("dbo.Permissions", "ApplicationOwnerId");
            CreateIndex("dbo.PrincipalPermissions", "LastModifiedBy_Id");
            CreateIndex("dbo.PrincipalPermissions", "AddedBy_Id");
            CreateIndex("dbo.PrincipalPermissions", "DataOwnerCenterId");
            CreateIndex("dbo.PrincipalPermissions", "DataOwnerId");
            CreateIndex("dbo.PrincipalPermissions", "ApplicationOwnerId");
            CreateIndex("dbo.PrincipalPermissions", "UserId");
            CreateIndex("dbo.Users", "Group_Id");
            AddForeignKey("dbo.ProductSupplierGuarantees", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductSupplierGuarantees", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventComments", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventComments", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityCommentTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityCommentTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ItemImages", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ItemImages", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Users", "Group_Id", "dbo.Groups", "Id");
            AddForeignKey("dbo.Groups", "Principal_Id", "dbo.ApplicationOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Groups", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Groups", "DataOwnerCenterId", "dbo.DataOwnerCenters", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Groups", "DataOwnerId", "dbo.DataOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Groups", "ApplicationOwnerId", "dbo.ApplicationOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Groups", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.DiscountCodes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.DiscountCodes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyPersonnelRoutes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyPersonnelRoutes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Clearances", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Clearances", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BaseTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BaseValues", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BaseValues", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BaseTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BankAccounts", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BankAccounts", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.UsersStocks", "StockID", "dbo.Stocks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UsersStocks", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Stocks", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Companies", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Customers", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Baskets", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BasketNotes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BasketNotes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductTags", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductTags", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductTagValues", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductTagValues", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductRates", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductRates", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductPictures", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductPictures", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductGroups", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductGroups", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductComments", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductComments", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Manufactures", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Manufactures", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestRuleTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestRuleTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestRuleCalcTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestRuleCalcTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Suppliers", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Suppliers", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ReorderCalcTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ReorderCalcTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProducts", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.FiscalYears", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.FiscalYears", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProducts", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestSupplyTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestSupplyTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestStatus", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestStatus", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestProductDetails", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestProductDetails", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestProducts", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestProducts", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockHistoryOnHands", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockHistoryOnHands", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockActiveOnHands", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockActiveOnHands", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockOnHandSyncs", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockOnHandSyncs", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequests", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequests", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.ProductTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestRules", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StockProductRequestRules", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.MainProductGroups", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.MainProductGroups", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Products", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrderLineItems", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrders", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderPayments", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderPayments", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderLineItems", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderLineItems", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderStatusHistories", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderStatusHistories", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderClearances", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrderClearances", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrders", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PurchaseOrders", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CustomerShipAddresses", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CustomerShipAddresses", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreDeliveryPersons", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.DeliveryPersons", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.DeliveryPersons", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreDeliveryPersons", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreCalendarHistories", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CalendarTemplates", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CalendarTemplateOpenTimes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CalendarTemplateOpenTimes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CalendarTemplateHolidays", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CalendarTemplateHolidays", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CalendarTemplates", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreCalendarHistories", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreCalendars", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreCalendars", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreActivePriceLists", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreActivePriceLists", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreActiveOnhands", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreActiveOnhands", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreActions", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.StoreActions", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Stores", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Stores", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CityRegions", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CityRegions", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrders", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.IncompletePurchaseOrderLineItems", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CharValues", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CharTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CharGroups", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CharGroups", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CharTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CharValues", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Products", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BasketItems", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.BasketItems", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Baskets", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.RegionAreaPoints", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.RegionAreaPoints", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.RegionAreaLevelTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.RegionAreaLevelTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityDayAreas", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityPoints", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityPoints", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityVisitTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityVisitTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventTypes", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEventTypes", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEvents", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityEvents", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyPersonnels", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyOrgCharts", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyOrgCharts", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyPersonnels", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PersonnelDailyActivityDayAreas", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.RegionAreas", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.RegionAreas", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CustomerAreas", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CustomerAreas", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Customers", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyCenters", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.CompanyCenters", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Companies", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Stocks", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PrincipalPermissions", "UserId", "dbo.Users", "Id");
            AddForeignKey("dbo.Permissions", "Parent_Id", "dbo.Permissions", "Id");
            AddForeignKey("dbo.Permissions", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.Permissions", "DataOwnerCenterId", "dbo.DataOwnerCenters", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Permissions", "DataOwnerId", "dbo.DataOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Permissions", "ApplicationOwnerId", "dbo.ApplicationOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Permissions", "AddedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PrincipalPermissions", "LastModifiedBy_Id", "dbo.Users", "Id");
            AddForeignKey("dbo.PrincipalPermissions", "DataOwnerCenterId", "dbo.DataOwnerCenters", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PrincipalPermissions", "DataOwnerId", "dbo.DataOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PrincipalPermissions", "ApplicationOwnerId", "dbo.ApplicationOwners", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PrincipalPermissions", "AddedBy_Id", "dbo.Users", "Id");
        }
    }
}
