// <auto-generated />
namespace Anatoli.Cloud.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StockRequest20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StockRequest20));
        
        string IMigrationMetadata.Id
        {
            get { return "201601061211329_Stock-Request-20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
